// Generated by scripts/generate-reader-viewport-anchor.mjs. Do not edit.
// Source: packages/tools/src/reader-viewport-anchor.ts

/**
 * Shared reader viewport-anchor source.
 * After editing, run from the repository root:
 * pnpm -C my-reader-mobile prepare:reader-viewport-anchor
 *
 * This is the only hand-written DOM implementation. The generator emits the
 * desktop TypeScript and the Swift/Kotlin scripts executed in EPUB web views.
 * Do not edit those generated files directly.
 */

/** A text position that can be resolved again inside an EPUB document. */
export type ReaderViewportDomRange = {
  start: {
    cssSelector: string
    textNodeIndex: number
    charOffset?: number
  }
}

export type ReaderViewportCapture = {
  cssSelector: string
  domRange: ReaderViewportDomRange
  text: {
    before?: string
    highlight: string
    after?: string
  }
  yRatio: number
}

/** The text-quote fields Readium uses to resolve a sentence locator. */
export type ReaderTextLocator = {
  locations?: {
    cssSelector?: string
    [key: string]: unknown
  }
  text?: {
    before?: string
    highlight?: string
    after?: string
  }
}

/** The anchor's normalized position in the current viewport. */
export type ReaderViewportAnchorOffset = {
  xRatio: number
  yRatio: number
}

export type ReaderViewportLayoutState = {
  fontsLoaded: boolean
  clientHeight: number
  clientWidth: number
  scrollHeight: number
  scrollWidth: number
}

type TextPoint = {
  node: Text
  offset: number
}

type CaretPositionDocument = Document & {
  caretPositionFromPoint?: (
    x: number,
    y: number,
  ) => { offsetNode: Node; offset: number } | null
}

type CssWindow = Window & {
  CSS?: {
    escape?: (value: string) => string
  }
}

function cssEscape(window: Window, value: string): string {
  const css = (window as CssWindow).CSS
  if (typeof css?.escape === "function") {
    return css.escape(value)
  }
  return value.replace(/[^a-zA-Z0-9_-]/g, (character) => {
    return `\\${character.codePointAt(0)?.toString(16)} `
  })
}

/** Prefers a unique ID, then falls back to a deterministic element path. */
function stableCssSelector(window: Window, element: Element): string {
  const document = element.ownerDocument
  if (element.id) {
    const selector = `#${cssEscape(window, element.id)}`
    if (document.querySelectorAll(selector).length === 1) return selector
  }

  const parts: string[] = []
  let current: Element | null = element
  while (current) {
    let part = current.localName
    const currentName = current.localName
    const parent: Element | null = current.parentElement
    if (parent) {
      const siblings = [...parent.children].filter(
        (sibling) => sibling.localName === currentName,
      )
      if (siblings.length > 1) {
        part += `:nth-of-type(${siblings.indexOf(current) + 1})`
      }
    }
    parts.unshift(part)
    if (current.id) {
      const idSelector = `#${cssEscape(window, current.id)}`
      if (document.querySelectorAll(idSelector).length === 1) {
        parts[0] = idSelector
        break
      }
    }
    current = parent
  }
  return parts.join(" > ")
}

function firstTextDescendant(node: Node | undefined): Text | null {
  if (!node) return null
  if (node.nodeType === Node.TEXT_NODE) return node as Text
  const walker = node.ownerDocument?.createTreeWalker(
    node,
    NodeFilter.SHOW_TEXT,
  )
  return (walker?.nextNode() as Text | null) ?? null
}

function textPointAt(window: Window, x: number, y: number): TextPoint | null {
  const document = window.document
  const caretPosition = (
    document as CaretPositionDocument
  ).caretPositionFromPoint?.(x, y)
  if (caretPosition) {
    const node =
      caretPosition.offsetNode.nodeType === Node.TEXT_NODE
        ? (caretPosition.offsetNode as Text)
        : (firstTextDescendant(
            caretPosition.offsetNode.childNodes[caretPosition.offset],
          ) ?? firstTextDescendant(caretPosition.offsetNode))
    if (node) return { node, offset: caretPosition.offset }
  }

  const caretRange = document.caretRangeFromPoint?.(x, y)
  if (!caretRange) return null
  const node =
    caretRange.startContainer.nodeType === Node.TEXT_NODE
      ? (caretRange.startContainer as Text)
      : (firstTextDescendant(
          caretRange.startContainer.childNodes[caretRange.startOffset],
        ) ?? firstTextDescendant(caretRange.startContainer))
  return node ? { node, offset: caretRange.startOffset } : null
}

/**
 * Keeps anchors on visible text and prevents splitting a UTF-16 surrogate pair.
 */
function anchorCharacterOffset(text: string, requestedOffset: number): number {
  let offset = Math.min(Math.max(0, requestedOffset), text.length - 1)
  if (/\s/.test(text[offset])) {
    for (let distance = 1; distance < text.length; distance += 1) {
      const after = offset + distance
      if (after < text.length && !/\s/.test(text[after])) {
        offset = after
        break
      }
      const before = offset - distance
      if (before >= 0 && !/\s/.test(text[before])) {
        offset = before
        break
      }
    }
  }
  const code = text.charCodeAt(offset)
  if (code >= 0xdc00 && code <= 0xdfff && offset > 0) return offset - 1
  return offset
}

function pointRect(document: Document, point: TextPoint): DOMRect | null {
  const text = point.node.data
  if (!text.trim()) return null
  const offset = anchorCharacterOffset(text, point.offset)
  const length = String.fromCodePoint(text.codePointAt(offset)!).length
  const range = document.createRange()
  range.setStart(point.node, offset)
  range.setEnd(point.node, Math.min(text.length, offset + length))
  return range.getClientRects()[0] ?? range.getBoundingClientRect()
}

function pointHitsTextRect(x: number, y: number, rect: DOMRect): boolean {
  const tolerance = 2
  return (
    x >= rect.left - tolerance &&
    x <= rect.right + tolerance &&
    y >= rect.top - tolerance &&
    y <= rect.bottom + tolerance
  )
}

const READABLE_BLOCK_SELECTOR = [
  "address",
  "article",
  "aside",
  "blockquote",
  "body",
  "dd",
  "details",
  "dialog",
  "div",
  "dl",
  "dt",
  "fieldset",
  "figcaption",
  "figure",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "header",
  "hgroup",
  "li",
  "main",
  "nav",
  "ol",
  "p",
  "pre",
  "section",
  "table",
  "tbody",
  "td",
  "tfoot",
  "th",
  "thead",
  "tr",
  "ul",
].join(",")

function captureTextPoint(
  window: Window,
  point: TextPoint,
  rect: DOMRect,
): ReaderViewportCapture | null {
  const parent = point.node.parentElement
  if (!parent) return null
  const cssSelector = stableCssSelector(
    window,
    parent.closest(READABLE_BLOCK_SELECTOR) ?? parent,
  )
  const pointSelector = stableCssSelector(window, parent)
  const textNodes = [...parent.childNodes].filter(
    (node): node is Text => node.nodeType === Node.TEXT_NODE,
  )
  const textNodeIndex = textNodes.indexOf(point.node)
  if (textNodeIndex < 0) return null

  const content = point.node.data
  const charOffset = anchorCharacterOffset(content, point.offset)
  const highlight = String.fromCodePoint(content.codePointAt(charOffset)!)
  const before = content.slice(Math.max(0, charOffset - 32), charOffset)
  const after = content.slice(charOffset + highlight.length, charOffset + 33)

  return {
    cssSelector,
    domRange: {
      start: { cssSelector: pointSelector, textNodeIndex, charOffset },
    },
    text: {
      ...(before ? { before } : {}),
      highlight,
      ...(after ? { after } : {}),
    },
    yRatio: (rect.top + rect.height / 2) / window.innerHeight,
  }
}

const INTERACTIVE_POINT_SELECTOR =
  "a, button, input, select, textarea, summary, [contenteditable], [role='button'], [role='link']"

/** Captures readable text at a normalized viewport point. */
export function captureReaderPointAnchor(
  window: Window,
  xRatio: number,
  yRatio: number,
): ReaderViewportCapture | null {
  const selection = window.getSelection()
  if (selection && !selection.isCollapsed) return null
  const x = Math.min(1, Math.max(0, xRatio)) * window.innerWidth
  const y = Math.min(1, Math.max(0, yRatio)) * window.innerHeight
  const target = window.document.elementFromPoint?.(x, y)
  if (target?.closest(INTERACTIVE_POINT_SELECTOR)) return null
  const point = textPointAt(window, x, y)
  if (!point?.node.data.trim()) return null
  const rect = pointRect(window.document, point)
  return rect && pointHitsTextRect(x, y, rect)
    ? captureTextPoint(window, point, rect)
    : null
}

type VisibleTextCandidate = {
  node: Text
  rect: DOMRect
  direction: string
  writingMode: string
  order: [number, number]
}

function visibleRect(window: Window, rect: DOMRect): DOMRect | null {
  const left = Math.max(0, rect.left)
  const right = Math.min(window.innerWidth, rect.right)
  const top = Math.max(0, rect.top)
  const bottom = Math.min(window.innerHeight, rect.bottom)
  if (right <= left || bottom <= top) return null
  return {
    x: left,
    y: top,
    left,
    right,
    top,
    bottom,
    width: right - left,
    height: bottom - top,
    toJSON: () => ({}),
  } as DOMRect
}

function isHorizontallyPaginated(window: Window): boolean {
  const scrollingElement = window.document.scrollingElement
  if (!scrollingElement) return false
  const columnCount = Number.parseInt(
    window.getComputedStyle(window.document.documentElement).columnCount,
    10,
  )
  const viewportWidth = Math.max(
    window.innerWidth,
    scrollingElement.clientWidth,
  )
  const viewportHeight = Math.max(
    window.innerHeight,
    scrollingElement.clientHeight,
  )
  return (
    scrollingElement.scrollHeight <= viewportHeight + 1 &&
    (scrollingElement.scrollWidth > viewportWidth + 1 || columnCount > 1)
  )
}

function visibleTextOrder(
  window: Window,
  rect: DOMRect,
  direction: string,
  writingMode: string,
): [number, number] {
  const vertical = /^(?:vertical|sideways)-/u.test(writingMode)
  if (vertical) {
    return [writingMode.endsWith("-rl") ? -rect.right : rect.left, rect.top]
  }
  if (isHorizontallyPaginated(window)) {
    return [direction === "rtl" ? -rect.right : rect.left, rect.top]
  }
  return [rect.top, direction === "rtl" ? -rect.right : rect.left]
}

function pointInsideLeadingEdge(candidate: VisibleTextCandidate): {
  x: number
  y: number
} {
  const { direction, rect, writingMode } = candidate
  const vertical = /^(?:vertical|sideways)-/u.test(writingMode)
  if (vertical) {
    return {
      x: rect.left + rect.width / 2,
      y: rect.top + Math.min(1, rect.height / 2),
    }
  }
  return {
    x:
      direction === "rtl"
        ? rect.right - Math.min(1, rect.width / 2)
        : rect.left + Math.min(1, rect.width / 2),
    y: rect.top + rect.height / 2,
  }
}

/** Captures the first rendered text position in the current page or viewport. */
export function captureReaderViewportStartAnchor(
  window: Window,
): ReaderViewportCapture | null {
  const { document } = window
  const root = document.body ?? document.documentElement
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
  let best: VisibleTextCandidate | null = null
  let current = walker.nextNode()

  while (current) {
    const node = current as Text
    const parent = node.parentElement
    if (node.data.trim() && parent) {
      const style = window.getComputedStyle(parent)
      if (style.display !== "none" && style.visibility !== "hidden") {
        const range = document.createRange()
        range.selectNodeContents(node)
        for (const sourceRect of Array.from(range.getClientRects())) {
          const rect = visibleRect(window, sourceRect)
          if (!rect) continue
          const direction = style.direction || "ltr"
          const writingMode = style.writingMode || "horizontal-tb"
          const candidate: VisibleTextCandidate = {
            node,
            rect,
            direction,
            writingMode,
            order: visibleTextOrder(window, rect, direction, writingMode),
          }
          if (
            !best ||
            candidate.order[0] < best.order[0] ||
            (candidate.order[0] === best.order[0] &&
              candidate.order[1] < best.order[1])
          ) {
            best = candidate
          }
        }
      }
    }
    current = walker.nextNode()
  }

  if (!best) return null
  const point = pointInsideLeadingEdge(best)
  const textPoint = textPointAt(window, point.x, point.y)
  if (!textPoint?.node.data.trim()) return null
  const rect = pointRect(document, textPoint)
  return rect ? captureTextPoint(window, textPoint, rect) : null
}

/** Resolves a persisted DOM point to the single character used as its anchor. */
function rangeForReaderViewportDomRange(
  window: Window,
  domRange: ReaderViewportDomRange,
): Range | null {
  const point = domRange.start
  const element = window.document.querySelector(point.cssSelector)
  if (!element) return null
  const textNodes = [...element.childNodes].filter(
    (node): node is Text => node.nodeType === Node.TEXT_NODE,
  )
  const node = textNodes[point.textNodeIndex]
  if (!node || node.data.length === 0) return null
  const offset = anchorCharacterOffset(
    node.data,
    Math.min(point.charOffset ?? 0, node.data.length - 1),
  )
  const length = String.fromCodePoint(node.data.codePointAt(offset)!).length
  const range = window.document.createRange()
  range.setStart(node, offset)
  range.setEnd(node, Math.min(node.data.length, offset + length))
  return range
}

function matchingPrefixLength(first: string, second: string): number {
  const limit = Math.min(first.length, second.length)
  let length = 0
  while (length < limit && first[length] === second[length]) length += 1
  return length
}

function matchingSuffixLength(first: string, second: string): number {
  const limit = Math.min(first.length, second.length)
  let length = 0
  while (
    length < limit &&
    first[first.length - length - 1] === second[second.length - length - 1]
  ) {
    length += 1
  }
  return length
}

function textPointForOffset(
  window: Window,
  root: Element,
  offset: number,
  preferPreviousNode: boolean,
): TextPoint | null {
  const walker = window.document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
  const nodes: Text[] = []
  let current = walker.nextNode()
  while (current) {
    nodes.push(current as Text)
    current = walker.nextNode()
  }
  let consumed = 0
  let last: Text | null = null
  for (const [index, node] of nodes.entries()) {
    const end = consumed + node.data.length
    if (
      offset < end ||
      (offset === end && (preferPreviousNode || index === nodes.length - 1))
    ) {
      return {
        node,
        offset: Math.max(0, Math.min(node.data.length, offset - consumed)),
      }
    }
    last = node
    consumed = end
  }
  return last && offset === consumed
    ? { node: last, offset: last.data.length }
    : null
}

/** Resolves a Readium text-quote locator to its DOM range. */
function rangeForReaderTextLocator(
  window: Window,
  locator: ReaderTextLocator,
): Range | null {
  const highlight = locator.text?.highlight
  if (!highlight) return null
  let root: Element = window.document.body ?? window.document.documentElement
  const cssSelector = locator.locations?.cssSelector
  if (cssSelector) {
    try {
      root = window.document.querySelector(cssSelector) ?? root
    } catch {
      return null
    }
  }
  const content = root.textContent ?? ""
  let bestStart = -1
  let bestScore = -1
  let searchFrom = 0
  while (searchFrom <= content.length - highlight.length) {
    const start = content.indexOf(highlight, searchFrom)
    if (start < 0) break
    const end = start + highlight.length
    const score =
      matchingSuffixLength(
        content.slice(0, start),
        locator.text?.before ?? "",
      ) + matchingPrefixLength(content.slice(end), locator.text?.after ?? "")
    if (score > bestScore) {
      bestStart = start
      bestScore = score
    }
    searchFrom = start + Math.max(1, highlight.length)
  }
  if (bestStart < 0) return null
  const start = textPointForOffset(window, root, bestStart, false)
  const end = textPointForOffset(
    window,
    root,
    bestStart + highlight.length,
    true,
  )
  if (!start || !end) return null
  const range = window.document.createRange()
  range.setStart(start.node, start.offset)
  range.setEnd(end.node, end.offset)
  return range
}

/**
 * Samples around the viewport center and captures the closest rendered glyph.
 * Nearby samples handle centers that land in whitespace or between columns.
 */
export function captureReaderViewportAnchor(
  window: Window,
): ReaderViewportCapture | null {
  const { document } = window
  const centerX = window.innerWidth / 2
  const centerY = window.innerHeight / 2
  const offsets = [0, -0.08, 0.08, -0.16, 0.16]
  let best: { point: TextPoint; rect: DOMRect; distance: number } | null = null

  for (const yOffset of offsets) {
    for (const xOffset of offsets.slice(0, 3)) {
      const point = textPointAt(
        window,
        centerX + window.innerWidth * xOffset,
        centerY + window.innerHeight * yOffset,
      )
      if (!point?.node.data.trim()) continue
      const rect = pointRect(document, point)
      if (!rect) continue
      const distance = Math.hypot(
        rect.left + rect.width / 2 - centerX,
        rect.top + rect.height / 2 - centerY,
      )
      if (!best || distance < best.distance) best = { point, rect, distance }
    }
  }

  if (!best) return null
  return captureTextPoint(window, best.point, best.rect)
}

/** Returns whether the persisted anchor character intersects the viewport. */
export function isReaderViewportAnchorVisible(
  window: Window,
  domRange: ReaderViewportDomRange,
): boolean {
  return [
    ...(rangeForReaderViewportDomRange(window, domRange)?.getClientRects() ??
      []),
  ].some(
    (rect) =>
      rect.right > 0 &&
      rect.bottom > 0 &&
      rect.left < window.innerWidth &&
      rect.top < window.innerHeight,
  )
}

/** Returns whether a Readium sentence locator intersects the viewport. */
export function isReaderTextLocatorVisible(
  window: Window,
  locator: ReaderTextLocator,
): boolean {
  return [
    ...(rangeForReaderTextLocator(window, locator)?.getClientRects() ?? []),
  ].some(
    (rect) =>
      rect.right > 0 &&
      rect.bottom > 0 &&
      rect.left < window.innerWidth &&
      rect.top < window.innerHeight,
  )
}

/** Captures the anchor's normalized position before a reflow. */
export function readerViewportAnchorOffset(
  window: Window,
  domRange: ReaderViewportDomRange,
): ReaderViewportAnchorOffset | null {
  const rect = rangeForReaderViewportDomRange(
    window,
    domRange,
  )?.getClientRects()[0]
  if (!rect || window.innerWidth <= 0 || window.innerHeight <= 0) return null
  return {
    xRatio: (rect.left + rect.width / 2) / window.innerWidth,
    yRatio: (rect.top + rect.height / 2) / window.innerHeight,
  }
}

/** Restores the anchor's vertical viewport position after a reflow. */
export function restoreReaderViewportAnchorOffset(
  window: Window,
  domRange: ReaderViewportDomRange,
  yRatio: number,
): boolean {
  const rect = rangeForReaderViewportDomRange(
    window,
    domRange,
  )?.getClientRects()[0]
  if (!rect) return false
  const targetY = yRatio * window.innerHeight
  const currentY = rect.top + rect.height / 2
  window.scrollBy(0, currentY - targetY)
  return true
}

/** Captures the metrics used by platform adapters to detect settled layout. */
export function readerViewportLayoutState(
  window: Window,
): ReaderViewportLayoutState {
  const scrollingElement = window.document.scrollingElement
  return {
    fontsLoaded:
      !window.document.fonts || window.document.fonts.status === "loaded",
    clientHeight: scrollingElement?.clientHeight ?? window.innerHeight,
    clientWidth: scrollingElement?.clientWidth ?? window.innerWidth,
    scrollHeight: scrollingElement?.scrollHeight ?? 0,
    scrollWidth: scrollingElement?.scrollWidth ?? 0,
  }
}

/** Compares only dimensions that change when EPUB pagination or reflow moves. */
export function sameReaderViewportLayout(
  first: ReaderViewportLayoutState | null,
  second: ReaderViewportLayoutState,
): boolean {
  return Boolean(
    first &&
      first.clientHeight === second.clientHeight &&
      first.clientWidth === second.clientWidth &&
      first.scrollHeight === second.scrollHeight &&
      first.scrollWidth === second.scrollWidth,
  )
}

/**
 * Binds the shared helpers to the EPUB web view's window for native bridges.
 * Swift and Kotlin call these methods without passing the window explicitly.
 */
export function createReaderViewportAnchorRuntime(window: Window) {
  return {
    captureReaderViewportAnchor: () => captureReaderViewportAnchor(window),
    captureReaderViewportStartAnchor: () =>
      captureReaderViewportStartAnchor(window),
    captureReaderPointAnchor: (xRatio: number, yRatio: number) =>
      captureReaderPointAnchor(window, xRatio, yRatio),
    isReaderViewportAnchorVisible: (domRange: ReaderViewportDomRange) =>
      isReaderViewportAnchorVisible(window, domRange),
    isReaderTextLocatorVisible: (locator: ReaderTextLocator) =>
      isReaderTextLocatorVisible(window, locator),
    readerViewportLayoutState: () => readerViewportLayoutState(window),
    restoreReaderViewportAnchorOffset: (
      domRange: ReaderViewportDomRange,
      yRatio: number,
    ) => restoreReaderViewportAnchorOffset(window, domRange, yRatio),
  }
}
