// Install the Intl prerequisites and plural rules before i18next initializes.
import "@formatjs/intl-getcanonicallocales/polyfill.js"
import "@formatjs/intl-locale/polyfill.js"
import "@formatjs/intl-pluralrules/polyfill-force.js"
import "@formatjs/intl-pluralrules/locale-data/en.js"
import "@formatjs/intl-pluralrules/locale-data/zh.js"
import "@formatjs/intl-pluralrules/locale-data/ja.js"
import "@formatjs/intl-pluralrules/locale-data/ko.js"
import "@formatjs/intl-pluralrules/locale-data/es.js"
import "@formatjs/intl-pluralrules/locale-data/fr.js"
import "@formatjs/intl-pluralrules/locale-data/de.js"
import "@formatjs/intl-pluralrules/locale-data/pt.js"
import "@formatjs/intl-pluralrules/locale-data/it.js"
import "@formatjs/intl-pluralrules/locale-data/ru.js"
