// Generated by uniffi-bindgen-react-native
import installer from "./NativeAutomergeGenerated"

declare global {
  var __MYREADER_AUTOMERGE_RUST_INSTALLED__: boolean | undefined
  var __MYREADER_AUTOMERGE_BINDINGS_INITIALIZED__: boolean | undefined
}

// Register the rust crate with Hermes
// - global flags survive Metro module reloads in the same JS runtime.
if (!globalThis.__MYREADER_AUTOMERGE_RUST_INSTALLED__) {
  installer.installRustCrate()
  globalThis.__MYREADER_AUTOMERGE_RUST_INSTALLED__ = true
}

// Export the generated bindings to the app.
export * from "./generated/automerge"

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as automerge from "./generated/automerge"

// Initialize the generated bindings: mostly checksums, but also callbacks.
// - this must also remain idempotent across Metro module reloads.
if (!globalThis.__MYREADER_AUTOMERGE_BINDINGS_INITIALIZED__) {
  automerge.default.initialize()
  globalThis.__MYREADER_AUTOMERGE_BINDINGS_INITIALIZED__ = true
}

// This provides parity with the index.web.ts version of this file.
// The web version relies on an asynchronous fetch, which this doesn't
// need, so we just no-op.
export async function uniffiInitAsync() {
  // NOOP.
}

export {
  nativeApi,
  NativeAutomerge,
  NativeSyncState,
  Automerge,
} from "./useapi-adapter"

// Export the crates as individually namespaced objects.
export default {
  automerge,
}
