// Generated from the Rust transport contract. Do not edit.
// Run `pnpm core:generate-contract` from the repository root to regenerate.

import type { ReaderAnnotationColor } from "@my-reader/tools/reader-annotations"
import type { ReaderLocator } from "@my-reader/tools/reader-toc"

// This file has been generated by Specta. Do not edit this file manually.
export type AsyncTransportRequest = AsyncTransportRequest_Serialize | AsyncTransportRequest_Deserialize;

export type AsyncTransportRequest_Deserialize = { domain: "catalog"; request: CatalogAsyncRequest } | { domain: "content"; request: ContentRequest } | { domain: "reading"; request: ReadingRequest } | { domain: "registry"; request: RegistryRequest_Deserialize } | { domain: "sync"; request: SyncAsyncRequest };

export type AsyncTransportRequest_Serialize = { domain: "catalog"; request: CatalogAsyncRequest } | { domain: "content"; request: ContentRequest } | { domain: "reading"; request: ReadingRequest } | { domain: "registry"; request: RegistryRequest_Serialize } | { domain: "sync"; request: SyncAsyncRequest };

export type AsyncTransportResponse = AsyncTransportResponse_Serialize | AsyncTransportResponse_Deserialize;

export type AsyncTransportResponse_Deserialize = { domain: "catalog"; response: CatalogAsyncResponse } | { domain: "content"; response: ContentResponse } | { domain: "reading"; response: ReadingResponse } | { domain: "registry"; response: RegistryResponse_Deserialize } | { domain: "sync"; response: SyncAsyncResponse };

export type AsyncTransportResponse_Serialize = { domain: "catalog"; response: CatalogAsyncResponse } | { domain: "content"; response: ContentResponse } | { domain: "reading"; response: ReadingResponse } | { domain: "registry"; response: RegistryResponse_Serialize } | { domain: "sync"; response: SyncAsyncResponse };

export type BookCoverThumbnailCache = {
	id: string,
	bookId: number,
	coverIdentity: string,
	thumbnailVersion: string,
	widthPx: number,
	heightPx: number,
	fileName: string,
	fileSizeBytes: number,
	createdAt: number,
	updatedAt: number,
};

export type BookCoverThumbnailCachePatch = {
	bookId: number,
	coverIdentity: string,
	thumbnailVersion: string,
	widthPx: number,
	heightPx: number,
	fileName: string,
	fileSizeBytes: number,
};

export type BookDetail = {
	formatSizes: FormatSize[],
	identifiers: BookIdentifier[],
} & BookEntry;

export type BookEntry = {
	id: number,
	title: string,
	titleSort: string,
	authorSort: string,
	authors: string[],
	tags: string[],
	series: string | null,
	seriesIndex: number | null,
	formats: string[],
	hasCover: boolean,
	path: string,
	timestamp: string | null,
	pubdate: string | null,
	lastModified: string | null,
	comment: string | null,
	publisher: string | null,
	languages: string[],
	rating: number | null,
	uuid: string | null,
};

export type BookFormat = {
	format: string,
	name: string,
	sizeBytes: number,
	relativePath: string,
};

export type BookIdentifier = {
	idType: string,
	value: string,
};

export type BookSummary = {
	id: number,
	path: string,
	hasCover: boolean,
	formats: string[],
	formatPaths: string[],
};

export type CatalogAsyncRequest = { operation: "countBooks"; input: {
	libraryRootPath: string,
} } | { operation: "listBooks"; input: {
	libraryRootPath: string,
} } | { operation: "listBooksPage"; input: {
	libraryRootPath: string,
	offset: number,
	limit: number,
	sortBy: string | null,
	search: string | null,
} } | { operation: "listBooksPageByLastRead"; input: {
	libraryRootPath: string,
	sidecarRootPath: string,
	offset: number,
	limit: number,
	search: string | null,
} } | { operation: "getBookDetail"; input: {
	libraryRootPath: string,
	bookId: number,
} } | { operation: "listSeriesBooks"; input: {
	libraryRootPath: string,
	seriesName: string,
	excludeBookId: number | null,
} } | { operation: "getLibraryUuid"; input: {
	libraryRootPath: string,
} } | { operation: "listBookSummaries"; input: {
	libraryRootPath: string,
} } | { operation: "listBookFormats"; input: {
	libraryRootPath: string,
	bookId: number,
} };

export type CatalogAsyncResponse = { operation: "countBooks"; output: number } | { operation: "listBooks"; output: BookEntry[] } | { operation: "listBooksPage"; output: PaginatedBooks } | { operation: "listBooksPageByLastRead"; output: PaginatedBooks } | { operation: "getBookDetail"; output: BookDetail } | { operation: "listSeriesBooks"; output: BookEntry[] } | { operation: "getLibraryUuid"; output: string } | { operation: "listBookSummaries"; output: BookSummary[] } | { operation: "listBookFormats"; output: BookFormat[] };

export type CatalogSyncRequest = { operation: "validateLibrary"; input: {
	libraryRootPath: string,
} };

export type CatalogSyncResponse = { operation: "validateLibrary"; output: boolean };

export type ContentRequest = { operation: "listReadingFormats"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
} } | { operation: "setReadingFormat"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	bookId: number,
	format: string | null,
} } | { operation: "getFileState"; input: {
	sidecarRootPath: string,
	path: string,
} } | { operation: "listFileStates"; input: {
	sidecarRootPath: string,
} } | { operation: "upsertFileState"; input: {
	sidecarRootPath: string,
	path: string,
	update: FileStateUpdate,
} } | { operation: "deleteFileState"; input: {
	sidecarRootPath: string,
	path: string,
} } | { operation: "finalizeDownloadedFile"; input: {
	sidecarRootPath: string,
	relativePath: string,
	localPath: string,
} } | { operation: "markFileRemoteOnly"; input: {
	sidecarRootPath: string,
	relativePath: string,
} } | { operation: "listCoverThumbnailCache"; input: {
	sidecarRootPath: string,
	thumbnailVersion: string,
	widthPx: number,
	heightPx: number,
} } | { operation: "upsertCoverThumbnailCache"; input: {
	sidecarRootPath: string,
	patch: BookCoverThumbnailCachePatch,
} } | { operation: "deleteCoverThumbnailCache"; input: {
	sidecarRootPath: string,
	bookId: number,
	thumbnailVersion: string,
	widthPx: number,
	heightPx: number,
} } | { operation: "clearCoverThumbnailCache"; input: {
	sidecarRootPath: string,
} };

export type ContentResponse = { operation: "listReadingFormats"; output: { [key in string]: string } } | { operation: "setReadingFormat"; output: null } | { operation: "getFileState"; output: FileState | null } | { operation: "listFileStates"; output: FileState[] } | { operation: "upsertFileState"; output: null } | { operation: "deleteFileState"; output: null } | { operation: "finalizeDownloadedFile"; output: DownloadedFile } | { operation: "markFileRemoteOnly"; output: null } | { operation: "listCoverThumbnailCache"; output: BookCoverThumbnailCache[] } | { operation: "upsertCoverThumbnailCache"; output: null } | { operation: "deleteCoverThumbnailCache"; output: null } | { operation: "clearCoverThumbnailCache"; output: null };

export type DataSource = DataSource_Serialize | DataSource_Deserialize;

export type DataSource_Deserialize = ({ local: {
	type: "local",
} & {
	id: string,
	name: string,
	enabled?: boolean,
	readonly?: boolean | null,
} & {
	rootPath: string,
} | {
	root_path: string,
} & {
	createdAt?: number | null,
} | {
	created_at?: number | null,
} }) & { onedrive?: never; webdav?: never } | ({ webdav: {
	type: "webdav",
} & {
	id: string,
	name: string,
	enabled?: boolean,
	endpoint: string,
	username: string,
	readonly?: boolean | null,
} & {
	rootPath?: string | null,
} | {
	root_path?: string | null,
} & {
	hasPassword?: boolean,
} | {
	has_password?: boolean,
} & {
	credentialReference?: string | null,
} | {
	credential_reference?: string | null,
} & {
	createdAt?: number | null,
} | {
	created_at?: number | null,
} }) & { local?: never; onedrive?: never } | ({ onedrive: {
	type: "onedrive",
} & {
	id: string,
	name: string,
	enabled?: boolean,
	email?: string | null,
	readonly?: boolean | null,
} & {
	clientId: string,
} | {
	client_id: string,
} & {
	tenantId?: string | null,
} | {
	tenant_id?: string | null,
} & {
	displayName?: string | null,
} | {
	display_name?: string | null,
} & {
	rootPath?: string | null,
} | {
	root_path?: string | null,
} & {
	hasRefreshToken?: boolean,
} | {
	has_refresh_token?: boolean,
} & {
	credentialReference?: string | null,
} | {
	credential_reference?: string | null,
} & {
	createdAt?: number | null,
} | {
	created_at?: number | null,
} }) & { local?: never; webdav?: never };

export type DataSource_Serialize = ({ type: "local"; id: string; name: string; enabled: boolean; rootPath: string; readonly: boolean | null; createdAt: number | null }) & { clientId?: never; credentialReference?: never; displayName?: never; email?: never; endpoint?: never; hasPassword?: never; hasRefreshToken?: never; tenantId?: never; username?: never } | ({ type: "webdav"; id: string; name: string; enabled: boolean; endpoint: string; username: string; rootPath: string | null; hasPassword: boolean; credentialReference: string | null; readonly: boolean | null; createdAt: number | null }) & { clientId?: never; displayName?: never; email?: never; hasRefreshToken?: never; tenantId?: never } | ({ type: "onedrive"; id: string; name: string; enabled: boolean; clientId: string; tenantId: string | null; displayName: string | null; email: string | null; rootPath: string | null; hasRefreshToken: boolean; credentialReference: string | null; readonly: boolean | null; createdAt: number | null }) & { endpoint?: never; hasPassword?: never; username?: never };

export type DeviceRegistry = DeviceRegistry_Serialize | DeviceRegistry_Deserialize;

export type DeviceRegistry_Deserialize = {
	schemaVersion?: number,
	dataSources?: DataSource_Deserialize[],
	libraries?: Library[],
	activeLibraryId?: string | null,
};

export type DeviceRegistry_Serialize = {
	schemaVersion: number,
	dataSources: DataSource_Serialize[],
	libraries: Library[],
	activeLibraryId: string | null,
};

export type DownloadRequest = { operation: "findActive"; input: {
	libraryId: string,
	relativePath: string,
} } | { operation: "enqueue"; input: {
	id: string,
	libraryId: string,
	bookId: string | null,
	format: string | null,
	relativePath: string,
	label: string,
} } | { operation: "claimReady" } | { operation: "claim"; input: {
	taskId: string,
} } | { operation: "markStarted"; input: {
	taskId: string,
} } | { operation: "reportProgress"; input: {
	taskId: string,
	received: number,
	total: number,
} } | { operation: "complete"; input: {
	taskId: string,
} } | { operation: "fail"; input: {
	taskId: string,
	error: string,
} } | { operation: "cancel"; input: {
	taskId: string,
} } | { operation: "list" } | { operation: "release"; input: {
	taskId: string,
} } | { operation: "clearFinished" };

export type DownloadResponse = { operation: "findActive"; output: DownloadTask | null } | { operation: "enqueue"; output: EnqueuedDownloadTask } | { operation: "claimReady"; output: DownloadTask[] } | { operation: "claim"; output: DownloadTask | null } | { operation: "markStarted"; output: DownloadTask | null } | { operation: "reportProgress"; output: DownloadTask | null } | { operation: "complete"; output: DownloadTask | null } | { operation: "fail"; output: DownloadTask | null } | { operation: "cancel"; output: boolean } | { operation: "list"; output: DownloadTask[] } | { operation: "release"; output: boolean } | { operation: "clearFinished"; output: null };

export type DownloadTask = {
	id: string,
	libraryId: string,
	bookId: string | null,
	format: string | null,
	relativePath: string,
	label: string,
	status: DownloadTaskStatus,
	progress: number,
	error: string | null,
};

export type DownloadTaskStatus = "queued" | "starting" | "downloading" | "done" | "error" | "cancelled";

export type DownloadedFile = {
	size: number,
	mtimeMs: number,
};

export type EnqueuedDownloadTask = {
	task: DownloadTask,
	inserted: boolean,
};

export type FileState = {
	id: string,
	path: string,
	localState: "present" | "remote_only" | "local_only" | "dirty_push",
	localBlake3: string | null,
	localSize: number | null,
	localMtime: number | null,
	updatedAt: number,
};

export type FileStateUpdate = {
	localState: "present" | "remote_only" | "local_only" | "dirty_push",
	localBlake3: string | null,
	localSize: number | null,
	localMtime: number | null,
};

export type FormatSize = {
	format: string,
	sizeBytes: number,
};

export type Library = {
	id: string,
	name: string,
	path: string,
	bookCount?: number,
	metadataUri?: string | null,
	addedAt?: number | null,
	dataSourceId?: string | null,
	sourceType?: string | null,
	sourcePath?: string | null,
	metadataEtag?: string | null,
	securityScopedBookmark?: SecurityScopedBookmark | null,
};

export type LibraryResult = LibraryResult_Serialize | LibraryResult_Deserialize;

export type LibraryResult_Deserialize = {
	registry: DeviceRegistry_Deserialize,
	library: Library,
};

export type LibraryResult_Serialize = {
	registry: DeviceRegistry_Serialize,
	library: Library,
};

export type LocalLibraryRequest = {
	libraryRootPath: string,
	path: string,
	sidecarContainerParentPath?: string | null,
	name?: string | null,
	metadataUri?: string | null,
	addedAt?: number | null,
	securityScopedBookmark?: SecurityScopedBookmark | null,
};

export type PaginatedBooks = {
	items: BookEntry[],
	total: number,
};

export type ReaderAnnotation = {
	id: string,
	bookId: number,
	format: string,
	kind: "highlight",
	locator: ReaderLocator,
	color: ReaderAnnotationColor,
	note: string | null,
	createdAt: number,
	updatedAt: number,
};

export type ReaderBookmark = {
	id: string,
	bookId: number,
	format: string,
	locatorKey: string,
	locator: ReaderLocator,
	createdAt: number,
	updatedAt: number,
};

export type ReadingPosition = {
	bookId: number,
	format: string,
	locator: ReaderLocator,
	displayProgression: number | null,
	updatedAt: number,
	conflictCount: number,
};

export type ReadingPositionCandidate = {
	operationId: string,
	locator: ReaderLocator,
	displayProgression: number | null,
	recordedAt: number,
	replicaId: string,
};

export type ReadingRequest = { operation: "listFavoriteBookIds"; input: {
	sidecarRootPath: string,
} } | { operation: "setFavoriteBook"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	bookId: number,
	isFavorite: boolean,
	recordedAtMs: number,
} } | { operation: "getReadingPosition"; input: {
	sidecarRootPath: string,
	bookId: number,
	format: string,
} } | { operation: "listReadingPositions"; input: {
	sidecarRootPath: string,
} } | { operation: "setReadingPosition"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	bookId: number,
	format: string,
	locator: ReaderLocator,
	displayProgression: number | null,
	recordedAtMs: number,
} } | { operation: "listReadingPositionCandidates"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	bookId: number,
	format: string,
	nowMs: number,
} } | { operation: "selectReadingPositionCandidate"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	bookId: number,
	format: string,
	operationId: string,
	recordedAtMs: number,
} } | { operation: "listReaderBookmarks"; input: {
	sidecarRootPath: string,
	bookId: number,
	format: string,
} } | { operation: "addReaderBookmark"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	bookId: number,
	format: string,
	locatorKey: string,
	locator: ReaderLocator,
	recordedAtMs: number,
} } | { operation: "removeReaderBookmark"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	bookId: number,
	format: string,
	locatorKey: string,
	recordedAtMs: number,
} } | { operation: "listReaderAnnotations"; input: {
	sidecarRootPath: string,
	bookId: number,
	format: string,
} } | { operation: "addReaderAnnotation"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	bookId: number,
	format: string,
	locator: ReaderLocator,
	color: ReaderAnnotationColor,
	note: string | null,
	recordedAtMs: number,
} } | { operation: "updateReaderAnnotation"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	bookId: number,
	format: string,
	id: string,
	color: ReaderAnnotationColor,
	note: string | null,
	recordedAtMs: number,
} } | { operation: "removeReaderAnnotation"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	bookId: number,
	format: string,
	id: string,
	recordedAtMs: number,
} } | { operation: "addReadingSessionInterval"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	id: string,
	bookId: number,
	format: string,
	localDay: string,
	startedAtMs: number,
	durationSeconds: number,
	recordedAtMs: number,
} } | { operation: "addReadingCompletion"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	id: string,
	bookId: number,
	format: string,
	localDay: string,
	completedAtMs: number,
	recordedAtMs: number,
} } | { operation: "getReadingStatistics"; input: {
	sidecarRootPath: string,
	libraryRootPath: string,
	startDay: string,
	endDay: string,
} };

export type ReadingResponse = { operation: "listFavoriteBookIds"; output: number[] } | { operation: "setFavoriteBook"; output: null } | { operation: "getReadingPosition"; output: ReadingPosition | null } | { operation: "listReadingPositions"; output: ReadingPosition[] } | { operation: "setReadingPosition"; output: null } | { operation: "listReadingPositionCandidates"; output: ReadingPositionCandidate[] } | { operation: "selectReadingPositionCandidate"; output: null } | { operation: "listReaderBookmarks"; output: ReaderBookmark[] } | { operation: "addReaderBookmark"; output: ReaderBookmark } | { operation: "removeReaderBookmark"; output: null } | { operation: "listReaderAnnotations"; output: ReaderAnnotation[] } | { operation: "addReaderAnnotation"; output: ReaderAnnotation } | { operation: "updateReaderAnnotation"; output: ReaderAnnotation } | { operation: "removeReaderAnnotation"; output: null } | { operation: "addReadingSessionInterval"; output: null } | { operation: "addReadingCompletion"; output: boolean } | { operation: "getReadingStatistics"; output: ReadingStatistics };

export type ReadingStatistics = {
	days: { [key in string]: number },
	totalDurationSeconds: number,
	longestStreakDays: number,
	completedBooks: number,
};

export type RegistryRequest = RegistryRequest_Serialize | RegistryRequest_Deserialize;

export type RegistryRequest_Deserialize = { operation: "initialize"; input: {
	registryPath: string,
	legacyRegistry: DeviceRegistry_Deserialize | null,
} } | { operation: "upsertDataSource"; input: {
	registryPath: string,
	source: DataSource_Deserialize,
} } | { operation: "prepareDataSource"; input: {
	source: DataSource_Deserialize,
} } | { operation: "validateDataSource"; input: {
	registryPath: string,
	source: DataSource_Deserialize,
} } | { operation: "removeDataSource"; input: {
	registryPath: string,
	dataSourceId: string,
} } | { operation: "registerLibrary"; input: {
	registryPath: string,
	library: Library,
} } | { operation: "replaceLibrary"; input: {
	registryPath: string,
	library: Library,
} } | { operation: "removeLibrary"; input: {
	registryPath: string,
	libraryId: string,
} } | { operation: "switchLibrary"; input: {
	registryPath: string,
	libraryId: string,
} } | { operation: "addLocalLibrary"; input: {
	registryPath: string,
	request: LocalLibraryRequest,
} } | { operation: "testRemoteDataSource"; input: {
	source: DataSource_Deserialize,
	credential: RemoteCredential,
} } | { operation: "listRemoteDirectories"; input: {
	registryPath: string,
	dataSourceId: string,
	path: string,
	credential: RemoteCredential,
} } | { operation: "addRemoteLibrary"; input: {
	registryPath: string,
	request: RemoteLibraryRequest,
	credential: RemoteCredential,
} } | { operation: "refreshRemoteLibrary"; input: {
	registryPath: string,
	libraryId: string,
	localRootPath: string,
	credential: RemoteCredential,
} };

export type RegistryRequest_Serialize = { operation: "initialize"; input: {
	registryPath: string,
	legacyRegistry: DeviceRegistry_Serialize | null,
} } | { operation: "upsertDataSource"; input: {
	registryPath: string,
	source: DataSource_Serialize,
} } | { operation: "prepareDataSource"; input: {
	source: DataSource_Serialize,
} } | { operation: "validateDataSource"; input: {
	registryPath: string,
	source: DataSource_Serialize,
} } | { operation: "removeDataSource"; input: {
	registryPath: string,
	dataSourceId: string,
} } | { operation: "registerLibrary"; input: {
	registryPath: string,
	library: Library,
} } | { operation: "replaceLibrary"; input: {
	registryPath: string,
	library: Library,
} } | { operation: "removeLibrary"; input: {
	registryPath: string,
	libraryId: string,
} } | { operation: "switchLibrary"; input: {
	registryPath: string,
	libraryId: string,
} } | { operation: "addLocalLibrary"; input: {
	registryPath: string,
	request: LocalLibraryRequest,
} } | { operation: "testRemoteDataSource"; input: {
	source: DataSource_Serialize,
	credential: RemoteCredential,
} } | { operation: "listRemoteDirectories"; input: {
	registryPath: string,
	dataSourceId: string,
	path: string,
	credential: RemoteCredential,
} } | { operation: "addRemoteLibrary"; input: {
	registryPath: string,
	request: RemoteLibraryRequest,
	credential: RemoteCredential,
} } | { operation: "refreshRemoteLibrary"; input: {
	registryPath: string,
	libraryId: string,
	localRootPath: string,
	credential: RemoteCredential,
} };

export type RegistryResponse = RegistryResponse_Serialize | RegistryResponse_Deserialize;

export type RegistryResponse_Deserialize = { operation: "initialize"; output: DeviceRegistry_Deserialize } | { operation: "upsertDataSource"; output: DeviceRegistry_Deserialize } | { operation: "prepareDataSource"; output: DataSource_Deserialize } | { operation: "validateDataSource"; output: null } | { operation: "removeDataSource"; output: DeviceRegistry_Deserialize } | { operation: "registerLibrary"; output: DeviceRegistry_Deserialize } | { operation: "replaceLibrary"; output: DeviceRegistry_Deserialize } | { operation: "removeLibrary"; output: DeviceRegistry_Deserialize } | { operation: "switchLibrary"; output: DeviceRegistry_Deserialize } | { operation: "addLocalLibrary"; output: LibraryResult_Deserialize } | { operation: "testRemoteDataSource"; output: null } | { operation: "listRemoteDirectories"; output: RemoteDirectoryEntry[] } | { operation: "addRemoteLibrary"; output: LibraryResult_Deserialize } | { operation: "refreshRemoteLibrary"; output: LibraryResult_Deserialize };

export type RegistryResponse_Serialize = { operation: "initialize"; output: DeviceRegistry_Serialize } | { operation: "upsertDataSource"; output: DeviceRegistry_Serialize } | { operation: "prepareDataSource"; output: DataSource_Serialize } | { operation: "validateDataSource"; output: null } | { operation: "removeDataSource"; output: DeviceRegistry_Serialize } | { operation: "registerLibrary"; output: DeviceRegistry_Serialize } | { operation: "replaceLibrary"; output: DeviceRegistry_Serialize } | { operation: "removeLibrary"; output: DeviceRegistry_Serialize } | { operation: "switchLibrary"; output: DeviceRegistry_Serialize } | { operation: "addLocalLibrary"; output: LibraryResult_Serialize } | { operation: "testRemoteDataSource"; output: null } | { operation: "listRemoteDirectories"; output: RemoteDirectoryEntry[] } | { operation: "addRemoteLibrary"; output: LibraryResult_Serialize } | { operation: "refreshRemoteLibrary"; output: LibraryResult_Serialize };

export type RemoteCredential = { type: "webdav"; password: string } | { type: "onedrive"; accessToken: string };

export type RemoteDirectoryEntry = {
	name: string,
	path: string,
	isDirectory: boolean,
};

export type RemoteLibraryRequest = {
	dataSourceId: string,
	sourcePath: string,
	librariesRootPath: string,
	librariesRootUri?: string | null,
	name?: string | null,
	addedAt?: number | null,
};

export type RetrySchedule = {
	retryCount: number,
	nextRetryAt: number,
};

export type ScheduledSync = {
	libraryId: string,
	generation: number,
	deadline: number,
};

export type SchedulerTransition = {
	schedules: ScheduledSync[],
	cancelTimersFor: string[],
	execution: SyncExecution | null,
	retry: RetrySchedule | null,
};

export type SecurityScopedBookmark = {
	bookmarkBase64: string,
	resolvedUri: string,
	stale: boolean,
};

export type SidecarStorageConfig = { kind: "local-direct"; root: string } | { kind: "webdav"; endpoint: string; username: string; password: string; root: string | null } | { kind: "onedrive"; accessToken: string; root: string | null };

export type SidecarSyncMode = "push_only" | "full";

export type SidecarSyncReport = {
	pushed: number,
	pulled: number,
};

export type SyncAsyncRequest = { operation: "recover"; input: {
	coordinatorId: string,
	sidecarRootPath: string,
	libraryId: string,
	nowMs: number,
} } | { operation: "requestContextualPull"; input: {
	coordinatorId: string,
	sidecarRootPath: string,
	libraryId: string,
	reason: string,
	nowMs: number,
	freshnessMs: number,
} } | { operation: "effectiveExecution"; input: {
	coordinatorId: string,
	sidecarRootPath: string,
	execution: SyncExecution,
	nowMs: number,
	freshnessMs: number,
} } | { operation: "fail"; input: {
	coordinatorId: string,
	sidecarRootPath: string,
	execution: SyncExecution,
	failureKind: SyncFailureKind,
	reason: string,
	nowMs: number,
	randomFraction: number,
} } | { operation: "runSidecar"; input: {
	taskId: string,
	sidecarRootPath: string,
	libraryRootPath: string,
	nowMs: number,
	mode: SidecarSyncMode,
	storage: SidecarStorageConfig,
} };

export type SyncAsyncResponse = { operation: "recover"; output: SchedulerTransition } | { operation: "requestContextualPull"; output: SchedulerTransition } | { operation: "effectiveExecution"; output: SyncExecution | null } | { operation: "fail"; output: SchedulerTransition } | { operation: "runSidecar"; output: SidecarSyncReport };

export type SyncExecution = {
	libraryId: string,
	mode: SyncMode,
	reasons: string[],
};

export type SyncFailureKind = "connectivity" | "configuration" | "credential" | "data_integrity" | "unexpected";

export type SyncMode = "push_only" | "full";

export type SyncRequest = { operation: "createCoordinator"; input: {
	coordinatorId: string,
} } | { operation: "request"; input: {
	coordinatorId: string,
	libraryId: string,
	mode: SidecarSyncMode,
	reason: string,
	timing: SyncTiming,
	nowMs: number,
} } | { operation: "flush"; input: {
	coordinatorId: string,
	libraryId: string,
	reason: string,
	nowMs: number,
} } | { operation: "begin"; input: {
	coordinatorId: string,
	libraryId: string,
	generation: number,
} } | { operation: "complete"; input: {
	coordinatorId: string,
	libraryId: string,
	nowMs: number,
} } | { operation: "setLibraryOnline"; input: {
	coordinatorId: string,
	libraryId: string,
	online: boolean,
	nowMs: number,
} } | { operation: "disposeCoordinator"; input: {
	coordinatorId: string,
} } | { operation: "readTaskProgress"; input: {
	taskId: string,
} } | { operation: "cancelTask"; input: {
	taskId: string,
} } | { operation: "releaseTask"; input: {
	taskId: string,
} };

export type SyncResponse = { operation: "createCoordinator"; output: boolean } | { operation: "request"; output: SchedulerTransition } | { operation: "flush"; output: SchedulerTransition } | { operation: "begin"; output: SchedulerTransition } | { operation: "complete"; output: SchedulerTransition } | { operation: "setLibraryOnline"; output: SchedulerTransition } | { operation: "disposeCoordinator"; output: SchedulerTransition } | { operation: "readTaskProgress"; output: SyncTaskProgress | null } | { operation: "cancelTask"; output: boolean } | { operation: "releaseTask"; output: boolean };

export type SyncTaskProgress = {
	taskId: string,
	stage: string,
	completed: number,
	total: number,
};

export type SyncTiming = "debounced" | "immediate";

export type SyncTransportRequest = { domain: "catalog"; request: CatalogSyncRequest } | { domain: "download"; request: DownloadRequest } | { domain: "sync"; request: SyncRequest };

export type SyncTransportResponse = { domain: "catalog"; response: CatalogSyncResponse } | { domain: "download"; response: DownloadResponse } | { domain: "sync"; response: SyncResponse };

export const CORE_CONTRACT_VERSION = 2 as const

type DomainOf<Request extends { domain: string }> = Request["domain"]

type RequestForDomain<
  Request,
  Domain extends string,
> = Extract<Request, { domain: Domain }> extends { request: infer Value }
  ? Value
  : never

type ResponseForDomain<
  Response,
  Domain extends string,
> = Extract<Response, { domain: Domain }> extends { response: infer Value }
  ? Value
  : never

type OperationOf<Request> = Request extends { operation: infer Operation }
  ? Operation & string
  : never

type InputForOperation<Request, Operation extends string> = Extract<
  Request,
  { operation: Operation }
> extends { input: infer Input }
  ? Input
  : undefined

type OutputForOperation<Response, Operation extends string> = Extract<
  Response,
  { operation: Operation }
> extends { output: infer Output }
  ? [Output] extends [null]
    ? void
    : Output
  : never

export type CoreSyncDomain = DomainOf<SyncTransportRequest>

export type CoreSyncOperation<
  Domain extends CoreSyncDomain,
> = OperationOf<RequestForDomain<SyncTransportRequest, Domain>>

export type CoreSyncInput<
  Domain extends CoreSyncDomain,
  Operation extends CoreSyncOperation<Domain>,
> = InputForOperation<RequestForDomain<SyncTransportRequest, Domain>, Operation>

export type CoreSyncOutput<
  Domain extends CoreSyncDomain,
  Operation extends CoreSyncOperation<Domain>,
> = OutputForOperation<
  ResponseForDomain<SyncTransportResponse, Domain>,
  Operation
>

export type CoreAsyncDomain = DomainOf<AsyncTransportRequest_Serialize>

export type CoreAsyncOperation<
  Domain extends CoreAsyncDomain,
> = OperationOf<RequestForDomain<AsyncTransportRequest_Serialize, Domain>>

export type CoreAsyncInput<
  Domain extends CoreAsyncDomain,
  Operation extends CoreAsyncOperation<Domain>,
> = InputForOperation<
  RequestForDomain<AsyncTransportRequest_Serialize, Domain>,
  Operation
>

export type CoreAsyncOutput<
  Domain extends CoreAsyncDomain,
  Operation extends CoreAsyncOperation<Domain>,
> = OutputForOperation<
  ResponseForDomain<AsyncTransportResponse_Serialize, Domain>,
  Operation
>
