// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listLibraries: () => typedError<LibraryInfo[], ErrorKind>(__TAURI_INVOKE("list_libraries")),
	listDataSources: () => typedError<DataSourceDto[], ErrorKind>(__TAURI_INVOKE("list_data_sources")),
	testWebdavConnection: (input: TestWebdavConnectionInput) => typedError<null, ErrorKind>(__TAURI_INVOKE("test_webdav_connection", { input })),
	addLibrary: (path: string, name: string | null) => typedError<LibraryInfo, ErrorKind>(__TAURI_INVOKE("add_library", { path, name })),
	addWebdavLibrary: (dataSourceId: string, remotePath: string, name: string | null) => typedError<LibraryInfo, ErrorKind>(__TAURI_INVOKE("add_webdav_library", { dataSourceId, remotePath, name })),
	addOnedriveLibrary: (dataSourceId: string, remotePath: string, name: string | null) => typedError<LibraryInfo, ErrorKind>(__TAURI_INVOKE("add_onedrive_library", { dataSourceId, remotePath, name })),
	refreshLibrary: (id: string) => typedError<LibraryInfo, ErrorKind>(__TAURI_INVOKE("refresh_library", { id })),
	refreshWebdavLibrary: (id: string) => typedError<LibraryInfo, ErrorKind>(__TAURI_INVOKE("refresh_webdav_library", { id })),
	refreshOnedriveLibrary: (id: string) => typedError<LibraryInfo, ErrorKind>(__TAURI_INVOKE("refresh_onedrive_library", { id })),
	addLocalDataSource: (input: NewLocalDataSourceInput) => typedError<DataSourceDto, ErrorKind>(__TAURI_INVOKE("add_local_data_source", { input })),
	addWebdavDataSource: (input: NewWebdavDataSourceInput) => typedError<DataSourceDto, ErrorKind>(__TAURI_INVOKE("add_webdav_data_source", { input })),
	removeLibrary: (id: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("remove_library", { id })),
	removeDataSource: (id: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("remove_data_source", { id })),
	switchLibrary: (id: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("switch_library", { id })),
	getActiveLibraryId: () => typedError<string | null, ErrorKind>(__TAURI_INVOKE("get_active_library_id")),
	webdavListFolders: (dataSourceId: string, path: string) => typedError<WebdavFolderEntry[], ErrorKind>(__TAURI_INVOKE("webdav_list_folders", { dataSourceId, path })),
	onedriveStartAuth: (input: OnedriveStartAuthInput) => typedError<OnedriveAuthResultDto, ErrorKind>(__TAURI_INVOKE("onedrive_start_auth", { input })),
	addOnedriveDataSource: (input: NewOnedriveDataSourceInput) => typedError<DataSourceDto, ErrorKind>(__TAURI_INVOKE("add_onedrive_data_source", { input })),
	onedriveListFolders: (dataSourceId: string, path: string) => typedError<OnedriveFolderEntry[], ErrorKind>(__TAURI_INVOKE("onedrive_list_folders", { dataSourceId, path })),
	getBooks: (libraryId: string | null) => typedError<BookEntry[], ErrorKind>(__TAURI_INVOKE("get_books", { libraryId })),
	getBooksPage: (libraryId: string | null, offset: number, limit: number, sortBy: string | null, search: string | null) => typedError<PaginatedBooks, ErrorKind>(__TAURI_INVOKE("get_books_page", { libraryId, offset, limit, sortBy, search })),
	getBookDetail: (libraryId: string | null, bookId: number) => typedError<BookDetail, ErrorKind>(__TAURI_INVOKE("get_book_detail", { libraryId, bookId })),
	getSeriesBooks: (libraryId: string | null, seriesName: string, excludeBookId: number | null) => typedError<BookEntry[], ErrorKind>(__TAURI_INVOKE("get_series_books", { libraryId, seriesName, excludeBookId })),
	getReadingProgress: (libraryId: string | null, bookId: number, format: string) => typedError<{
	libraryId: string,
	bookId: number,
	format: string,
	locator: any,
	updatedAt: number | null,
} | null, ErrorKind>(__TAURI_INVOKE("get_reading_progress", { libraryId, bookId, format })),
	setReadingProgress: (libraryId: string | null, bookId: number, format: string, locator: any) => typedError<null, ErrorKind>(__TAURI_INVOKE("set_reading_progress", { libraryId, bookId, format, locator })),
	getReaderUiPreferences: () => typedError<ReaderUiPreferences_Serialize, ErrorKind>(__TAURI_INVOKE("get_reader_ui_preferences")),
	setReaderUiPreferences: (preferences: ReaderUiPreferences_Deserialize) => typedError<null, ErrorKind>(__TAURI_INVOKE("set_reader_ui_preferences", { preferences })),
	prepareBookSource: (libraryId: string | null, bookId: number, format: string) => typedError<PreparedBookSource, ErrorKind>(__TAURI_INVOKE("prepare_book_source", { libraryId, bookId, format })),
	writeEpubReadiumManifest: (dirPath: string, manifest: any) => typedError<null, ErrorKind>(__TAURI_INVOKE("write_epub_readium_manifest", { dirPath, manifest })),
	closeBookStreamer: (libraryId: string, bookId: number) => typedError<null, ErrorKind>(__TAURI_INVOKE("close_book_streamer", { libraryId, bookId })),
	getCacheUsage: () => typedError<CacheUsageDto, ErrorKind>(__TAURI_INVOKE("get_cache_usage")),
	clearCache: () => typedError<null, ErrorKind>(__TAURI_INVOKE("clear_cache")),
	enforceCacheLimit: () => typedError<null, ErrorKind>(__TAURI_INVOKE("enforce_cache_limit")),
	syncListBackends: () => typedError<SyncBackendInfo[], ErrorKind>(__TAURI_INVOKE("sync_list_backends")),
	syncTestBackend: (id: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("sync_test_backend", { id })),
	syncListFileStates: (libraryId: string, filter: string | null) => typedError<FileStateRow[], ErrorKind>(__TAURI_INVOKE("sync_list_file_states", { libraryId, filter })),
	syncDownloadFile: (libraryId: string, dataSourceId: string, relativePath: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("sync_download_file", { libraryId, dataSourceId, relativePath })),
	syncEvictLocalFile: (libraryId: string, relativePath: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("sync_evict_local_file", { libraryId, relativePath })),
	syncDeleteFileEverywhere: (libraryId: string, dataSourceId: string, relativePath: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("sync_delete_file_everywhere", { libraryId, dataSourceId, relativePath })),
	syncDbNow: (libraryId: string, dataSourceId: string) => typedError<DbSyncReport, ErrorKind>(__TAURI_INVOKE("sync_db_now", { libraryId, dataSourceId })),
	syncDbForLibrary: (libraryId: string) => typedError<DbSyncReport, ErrorKind>(__TAURI_INVOKE("sync_db_for_library", { libraryId })),
};

/* Types */
/**  Extended book detail with format sizes and identifiers pre-loaded. */
export type BookDetail = {
	formatSizes: FormatSize[],
	identifiers: BookIdentifier[],
} & BookEntry;

/**  Flattened book entry from Calibre's metadata.db with all related data pre-joined. */
export type BookEntry = {
	id: number,
	title: string,
	authorSort: string,
	authors: string[],
	tags: string[],
	series: string | null,
	seriesIndex: number | null,
	formats: string[],
	hasCover: boolean,
	path: string,
	timestamp: string | null,
	pubdate: string | null,
	lastModified: string | null,
	comment: string | null,
	publisher: string | null,
	languages: string[],
	rating: number | null,
	uuid: string | null,
};

export type BookIdentifier = {
	idType: string,
	value: string,
};

export type CachePreferencesDto = {
	maxCacheSizeMb?: number,
	autoCleanupOnLaunch?: boolean,
};

export type CacheUsageDto = {
	totalBytes: number,
	maxBytes: number,
};

export type DataSourceDetailDto = { kind: "local"; root_path: string } | { kind: "webdav"; endpoint: string; username: string; has_password: boolean; root_path: string | null } | { kind: "onedrive"; client_id: string; tenant_id: string; has_refresh_token: boolean; root_path: string | null; user_name: string | null; user_email: string | null };

/**  Data source DTO for the frontend. For WebDAV only whether a password is configured is returned, to avoid echoing plaintext secrets on the settings page. */
export type DataSourceDto = {
	id: string,
	name: string,
	enabled: boolean,
} & DataSourceDetailDto;

export type DbSyncReport = {
	pushed: number,
	pulled: number,
};

export type ErrorKind = { kind: "Io"; message: string } | { kind: "Database"; message: string } | { kind: "NotFound"; message: string } | { kind: "Config"; message: string } | { kind: "Serialize"; message: string } | { kind: "Request"; message: string } | { kind: "Zip"; message: string } | { kind: "Task"; message: string } | { kind: "Auth"; message: string } | { kind: "Credential"; message: string } | { kind: "Sync"; message: string };

export type FileStateRow = {
	path: string,
	localState: string,
	localBlake3: string | null,
	localSize: number | null,
	localMtime: number | null,
};

/**  与前端 `FixedLayoutSettings` 对齐，作为机器本地偏好持久化在 `config.json` 的 `readerUi` 字段。 */
export type FixedLayoutSettingsDto = {
	readingLayout?: string,
	displayMode?: string,
	spreadMode?: string,
	zoomMode?: string,
	direction?: string,
	brightness?: number | null,
	pageGap?: number | null,
};

export type FormatSize = {
	format: string,
	sizeBytes: number,
};

export type LibraryInfo = {
	id: string,
	name: string,
	path: string,
	bookCount: number,
	sourceType: string | null,
	dataSourceId: string | null,
	sourcePath: string | null,
};

export type NewLocalDataSourceInput = {
	name: string,
	rootPath: string,
};

export type NewOnedriveDataSourceInput = {
	name: string,
	clientId: string | null,
	tenantId: string | null,
	rootPath: string | null,
	userName: string | null,
	userEmail: string | null,
	refreshToken: string | null,
};

export type NewWebdavDataSourceInput = {
	name: string,
	endpoint: string,
	username: string,
	password: string,
	rootPath: string | null,
};

export type OnedriveAuthResultDto = {
	accessToken: string,
	refreshToken: string,
	userName: string,
	userEmail: string | null,
};

export type OnedriveFolderEntry = {
	name: string,
	path: string,
	itemId: string | null,
};

export type OnedriveStartAuthInput = {
	clientId: string | null,
	tenantId: string | null,
};

export type PaginatedBooks = {
	items: BookEntry[],
	total: number,
};

export type PreparedBookSource = {
	format: string,
	filePath: string,
	extractedDirPath: string | null,
	extractedEntries: string[],
	streamerUrl: string | null,
};

export type ReaderSettingsDto = {
	theme?: string,
	fontFamily?: string,
	fontSize?: number | null,
	lineHeight?: number | null,
	paddingX?: number | null,
	readingLayout?: string,
	textAlign?: string,
	colCount?: string,
};

export type ReaderUiPreferences = ReaderUiPreferences_Serialize | ReaderUiPreferences_Deserialize;

export type ReaderUiPreferences_Deserialize = {
	version?: number,
	libraryViewMode?: string,
	fixedLayout?: FixedLayoutSettingsDto,
	cache?: CachePreferencesDto,
} & {
	reflowable?: ReflowableReaderPreferencesDto,
} | {
	reflow?: ReflowableReaderPreferencesDto,
};

export type ReaderUiPreferences_Serialize = {
	version: number,
	libraryViewMode: string,
	fixedLayout: FixedLayoutSettingsDto,
	reflowable: ReflowableReaderPreferencesDto,
	cache: CachePreferencesDto,
};

/**  Returned by `get_reading_progress`: JSON of a Readium `Locator` (compatible with `@readium/shared`). */
export type ReadingProgressDto = {
	libraryId: string,
	bookId: number,
	format: string,
	locator: any,
	updatedAt: number | null,
};

export type ReflowTtsDto = {
	ttsConfigId?: string,
	ttsSpeed?: number | null,
};

export type ReflowableReaderPreferencesDto = {
	settings?: ReaderSettingsDto,
	tts?: ReflowTtsDto,
};

export type SyncBackendInfo = {
	id: string,
	name: string,
	enabled: boolean,
	kind: string,
	summary: string,
	isLocalDirect: boolean,
};

export type TestWebdavConnectionInput = {
	endpoint: string,
	username: string,
	password: string,
	rootPath: string | null,
};

export type WebdavFolderEntry = {
	name: string,
	path: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

