// Auto-generated typed Tauri IPC bindings.
// Re-export from tauri-specta.ts (generated by Rust `cargo test`).
export type * from "./tauri-specta"

import { type ErrorKind, commands as raw } from "./tauri-specta"

type Result<T> =
  | { status: "ok"; data: T }
  | { status: "error"; error: ErrorKind }

function unwrap<T>(promise: Promise<Result<T>>): Promise<T> {
  return promise.then((r) => {
    if (r.status === "error") {
      const err = new Error(r.error.message)
      ;(err as Error & { kind: string }).kind = r.error.kind
      throw err
    }
    return r.data
  })
}

function wrap<T, A extends unknown[]>(
  fn: (...args: A) => Promise<Result<T>>,
): (...args: A) => Promise<T> {
  return (...args: A) => unwrap(fn(...args))
}

export const api = {
  listLibraries: wrap(raw.listLibraries),
  listDataSources: wrap(raw.listDataSources),
  testWebdavConnection: wrap(raw.testWebdavConnection),
  webdavListFolders: wrap(raw.webdavListFolders),
  onedriveStartAuth: wrap(raw.onedriveStartAuth),
  addOnedriveDataSource: wrap(raw.addOnedriveDataSource),
  onedriveListFolders: wrap(raw.onedriveListFolders),
  addLibrary: wrap(raw.addLibrary),
  addWebdavLibrary: wrap(raw.addWebdavLibrary),
  addOnedriveLibrary: wrap(raw.addOnedriveLibrary),
  refreshLibrary: wrap(raw.refreshLibrary),
  refreshWebdavLibrary: wrap(raw.refreshWebdavLibrary),
  refreshOnedriveLibrary: wrap(raw.refreshOnedriveLibrary),
  addLocalDataSource: wrap(raw.addLocalDataSource),
  addWebdavDataSource: wrap(raw.addWebdavDataSource),
  removeLibrary: wrap(raw.removeLibrary),
  removeDataSource: wrap(raw.removeDataSource),
  switchLibrary: wrap(raw.switchLibrary),
  getActiveLibraryId: wrap(raw.getActiveLibraryId),
  getBooks: wrap(raw.getBooks),
  getBooksPage: wrap(raw.getBooksPage),
  getBookDetail: wrap(raw.getBookDetail),
  getSeriesBooks: wrap(raw.getSeriesBooks),
  getReadingProgress: wrap(raw.getReadingProgress),
  setReadingProgress: wrap(raw.setReadingProgress),
  getReaderUiPreferences: wrap(raw.getReaderUiPreferences),
  setReaderUiPreferences: wrap(raw.setReaderUiPreferences),
  prepareBookSource: wrap(raw.prepareBookSource),
  writeEpubReadiumManifest: wrap(raw.writeEpubReadiumManifest),
  closeBookStreamer: wrap(raw.closeBookStreamer),
  getCacheUsage: wrap(raw.getCacheUsage),
  clearCache: wrap(raw.clearCache),
  enforceCacheLimit: wrap(raw.enforceCacheLimit),
  syncDbForLibrary: wrap(raw.syncDbForLibrary),
  checkBookFileState: wrap(raw.checkBookFileState),
  downloadBookFile: wrap(raw.downloadBookFile),
  deleteLocalBookFile: wrap(raw.deleteLocalBookFile),
  cancelBookDownload: wrap(raw.cancelBookDownload),
}
