// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listLibraries: () => typedError<LibraryInfo[], ErrorKind>(__TAURI_INVOKE("list_libraries")),
	listDataSources: () => typedError<DataSourceDto[], ErrorKind>(__TAURI_INVOKE("list_data_sources")),
	testWebdavConnection: (input: TestWebdavConnectionInput) => typedError<null, ErrorKind>(__TAURI_INVOKE("test_webdav_connection", { input })),
	addLibrary: (path: string, name: string | null) => typedError<LibraryInfo, ErrorKind>(__TAURI_INVOKE("add_library", { path, name })),
	addWebdavLibrary: (dataSourceId: string, remotePath: string, name: string | null) => typedError<LibraryInfo, ErrorKind>(__TAURI_INVOKE("add_webdav_library", { dataSourceId, remotePath, name })),
	addOnedriveLibrary: (dataSourceId: string, remotePath: string, name: string | null) => typedError<LibraryInfo, ErrorKind>(__TAURI_INVOKE("add_onedrive_library", { dataSourceId, remotePath, name })),
	refreshLibrary: (id: string) => typedError<LibraryInfo, ErrorKind>(__TAURI_INVOKE("refresh_library", { id })),
	refreshWebdavLibrary: (id: string) => typedError<LibraryInfo, ErrorKind>(__TAURI_INVOKE("refresh_webdav_library", { id })),
	refreshOnedriveLibrary: (id: string) => typedError<LibraryInfo, ErrorKind>(__TAURI_INVOKE("refresh_onedrive_library", { id })),
	addLocalDataSource: (input: NewLocalDataSourceInput) => typedError<DataSourceDto, ErrorKind>(__TAURI_INVOKE("add_local_data_source", { input })),
	addWebdavDataSource: (input: NewWebdavDataSourceInput) => typedError<DataSourceDto, ErrorKind>(__TAURI_INVOKE("add_webdav_data_source", { input })),
	removeLibrary: (id: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("remove_library", { id })),
	removeDataSource: (id: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("remove_data_source", { id })),
	switchLibrary: (id: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("switch_library", { id })),
	getActiveLibraryId: () => typedError<string | null, ErrorKind>(__TAURI_INVOKE("get_active_library_id")),
	webdavListFolders: (dataSourceId: string, path: string) => typedError<WebdavFolderEntry[], ErrorKind>(__TAURI_INVOKE("webdav_list_folders", { dataSourceId, path })),
	onedriveStartAuth: (input: OnedriveStartAuthInput) => typedError<OnedriveAuthResultDto, ErrorKind>(__TAURI_INVOKE("onedrive_start_auth", { input })),
	addOnedriveDataSource: (input: NewOnedriveDataSourceInput) => typedError<DataSourceDto, ErrorKind>(__TAURI_INVOKE("add_onedrive_data_source", { input })),
	onedriveListFolders: (dataSourceId: string, path: string) => typedError<OnedriveFolderEntry[], ErrorKind>(__TAURI_INVOKE("onedrive_list_folders", { dataSourceId, path })),
	getBooks: (libraryId: string | null) => typedError<BookEntry[], ErrorKind>(__TAURI_INVOKE("get_books", { libraryId })),
	getBooksPage: (libraryId: string | null, offset: number, limit: number, sortBy: string | null, search: string | null) => typedError<PaginatedBooks, ErrorKind>(__TAURI_INVOKE("get_books_page", { libraryId, offset, limit, sortBy, search })),
	getBookDetail: (libraryId: string | null, bookId: number) => typedError<BookDetail, ErrorKind>(__TAURI_INVOKE("get_book_detail", { libraryId, bookId })),
	getSeriesBooks: (libraryId: string | null, seriesName: string, excludeBookId: number | null) => typedError<BookEntry[], ErrorKind>(__TAURI_INVOKE("get_series_books", { libraryId, seriesName, excludeBookId })),
	listBookReadingFormats: (libraryId: string) => typedError<{ [key in string]: string }, ErrorKind>(__TAURI_INVOKE("list_book_reading_formats", { libraryId })),
	setBookReadingFormat: (libraryId: string, bookId: number, format: string | null) => typedError<null, ErrorKind>(__TAURI_INVOKE("set_book_reading_format", { libraryId, bookId, format })),
	listFavoriteBookIds: (libraryId: string | null) => typedError<number[], ErrorKind>(__TAURI_INVOKE("list_favorite_book_ids", { libraryId })),
	addFavoriteBook: (libraryId: string | null, bookId: number) => typedError<null, ErrorKind>(__TAURI_INVOKE("add_favorite_book", { libraryId, bookId })),
	removeFavoriteBook: (libraryId: string | null, bookId: number) => typedError<null, ErrorKind>(__TAURI_INVOKE("remove_favorite_book", { libraryId, bookId })),
	getReadingProgress: (libraryId: string | null, bookId: number, format: string) => typedError<{
	libraryId: string,
	bookId: number,
	format: string,
	locator: any,
	displayProgression: number | null,
	updatedAt: number | null,
} | null, ErrorKind>(__TAURI_INVOKE("get_reading_progress", { libraryId, bookId, format })),
	listReadingProgress: (libraryId: string | null) => typedError<ReadingProgressDto[], ErrorKind>(__TAURI_INVOKE("list_reading_progress", { libraryId })),
	setReadingProgress: (libraryId: string | null, bookId: number, format: string, locator: any, displayProgression: number | null) => typedError<null, ErrorKind>(__TAURI_INVOKE("set_reading_progress", { libraryId, bookId, format, locator, displayProgression })),
	listReadingPositionCandidates: (libraryId: string | null, bookId: number, format: string) => typedError<ReadingPositionCandidateDto[], ErrorKind>(__TAURI_INVOKE("list_reading_position_candidates", { libraryId, bookId, format })),
	selectReadingPositionCandidate: (libraryId: string | null, bookId: number, format: string, operationId: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("select_reading_position_candidate", { libraryId, bookId, format, operationId })),
	addReadingSessionInterval: (libraryId: string | null, id: string, bookId: number, format: string, localDay: string, startedAt: number | null, durationSeconds: number, updatedAt: number | null) => typedError<null, ErrorKind>(__TAURI_INVOKE("add_reading_session_interval", { libraryId, id, bookId, format, localDay, startedAt, durationSeconds, updatedAt })),
	addReadingCompletion: (libraryId: string | null, id: string, bookId: number, format: string, localDay: string, completedAt: number | null, updatedAt: number | null) => typedError<boolean, ErrorKind>(__TAURI_INVOKE("add_reading_completion", { libraryId, id, bookId, format, localDay, completedAt, updatedAt })),
	listReaderAnnotations: (libraryId: string | null, bookId: number, format: string) => typedError<ReaderAnnotationDto[], ErrorKind>(__TAURI_INVOKE("list_reader_annotations", { libraryId, bookId, format })),
	addReaderAnnotation: (libraryId: string | null, bookId: number, format: string, locator: any, color: string, note: string | null) => typedError<ReaderAnnotationDto, ErrorKind>(__TAURI_INVOKE("add_reader_annotation", { libraryId, bookId, format, locator, color, note })),
	updateReaderAnnotation: (libraryId: string | null, bookId: number, format: string, id: string, color: string, note: string | null) => typedError<ReaderAnnotationDto, ErrorKind>(__TAURI_INVOKE("update_reader_annotation", { libraryId, bookId, format, id, color, note })),
	deleteReaderAnnotation: (libraryId: string | null, bookId: number, format: string, id: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("delete_reader_annotation", { libraryId, bookId, format, id })),
	listReaderBookmarks: (libraryId: string | null, bookId: number, format: string) => typedError<ReaderBookmarkDto[], ErrorKind>(__TAURI_INVOKE("list_reader_bookmarks", { libraryId, bookId, format })),
	addReaderBookmark: (libraryId: string | null, bookId: number, format: string, locatorKey: string, locator: any) => typedError<ReaderBookmarkDto, ErrorKind>(__TAURI_INVOKE("add_reader_bookmark", { libraryId, bookId, format, locatorKey, locator })),
	deleteReaderBookmark: (libraryId: string | null, bookId: number, format: string, locatorKey: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("delete_reader_bookmark", { libraryId, bookId, format, locatorKey })),
	getReaderUiPreferences: () => typedError<ReaderUiPreferences_Serialize, ErrorKind>(__TAURI_INVOKE("get_reader_ui_preferences")),
	setReaderUiPreferences: (preferences: ReaderUiPreferences_Deserialize) => typedError<null, ErrorKind>(__TAURI_INVOKE("set_reader_ui_preferences", { preferences })),
	prepareBookSource: (libraryId: string | null, bookId: number, format: string) => typedError<PreparedBookSource, ErrorKind>(__TAURI_INVOKE("prepare_book_source", { libraryId, bookId, format })),
	writeEpubReadiumManifest: (dirPath: string, manifest: any) => typedError<null, ErrorKind>(__TAURI_INVOKE("write_epub_readium_manifest", { dirPath, manifest })),
	setReaderTrafficLightsVisible: (visible: boolean, x: number, y: number, reposition: boolean) => typedError<null, ErrorKind>(__TAURI_INVOKE("set_reader_traffic_lights_visible", { visible, x, y, reposition })),
	closeBookStreamer: (libraryId: string, bookId: number) => typedError<null, ErrorKind>(__TAURI_INVOKE("close_book_streamer", { libraryId, bookId })),
	syncDbForLibrary: (libraryId: string) => typedError<DbSyncReport, ErrorKind>(__TAURI_INVOKE("sync_db_for_library", { libraryId })),
	notifySidecarNetworkReconnected: () => typedError<null, ErrorKind>(__TAURI_INVOKE("notify_sidecar_network_reconnected")),
	checkBookFileState: (libraryId: string, bookId: number, format: string) => typedError<FileStateDto, ErrorKind>(__TAURI_INVOKE("check_book_file_state", { libraryId, bookId, format })),
	checkBookFileStates: (libraryId: string, requests: FileStateRequestDto[]) => typedError<BookFileStateDto[], ErrorKind>(__TAURI_INVOKE("check_book_file_states", { libraryId, requests })),
	downloadBookFile: (libraryId: string, bookId: number, format: string) => typedError<string, ErrorKind>(__TAURI_INVOKE("download_book_file", { libraryId, bookId, format })),
	deleteLocalBookFile: (libraryId: string, bookId: number, format: string) => typedError<null, ErrorKind>(__TAURI_INVOKE("delete_local_book_file", { libraryId, bookId, format })),
	cancelBookDownload: (libraryId: string, bookId: number, format: string) => typedError<boolean, ErrorKind>(__TAURI_INVOKE("cancel_book_download", { libraryId, bookId, format })),
};

/* Types */
/**  Extended book detail with format sizes and identifiers pre-loaded. */
export type BookDetail = {
	formatSizes: FormatSize[],
	identifiers: BookIdentifier[],
} & BookEntry;

/**  Flattened book entry from Calibre's metadata.db with all related data pre-joined. */
export type BookEntry = {
	id: number,
	title: string,
	authorSort: string,
	authors: string[],
	tags: string[],
	series: string | null,
	seriesIndex: number | null,
	formats: string[],
	hasCover: boolean,
	path: string,
	timestamp: string | null,
	pubdate: string | null,
	lastModified: string | null,
	comment: string | null,
	publisher: string | null,
	languages: string[],
	rating: number | null,
	uuid: string | null,
};

/**  Returned by `check_book_file_states`: keyed file cache state for a book format. */
export type BookFileStateDto = {
	bookId: number,
	format: string,
	path: string,
	localState: string,
	localSize: number | null,
};

export type BookIdentifier = {
	idType: string,
	value: string,
};

export type DataSourceDetailDto = { kind: "local"; root_path: string } | { kind: "webdav"; endpoint: string; username: string; has_password: boolean; root_path: string | null } | { kind: "onedrive"; client_id: string; tenant_id: string; has_refresh_token: boolean; root_path: string | null; user_name: string | null; user_email: string | null };

/**  Data source DTO for the frontend. For WebDAV only whether a password is configured is returned, to avoid echoing plaintext secrets on the settings page. */
export type DataSourceDto = {
	id: string,
	name: string,
	enabled: boolean,
} & DataSourceDetailDto;

export type DbSyncReport = {
	pushed: number,
	pulled: number,
};

export type ErrorKind = { kind: "Io"; message: string } | { kind: "Database"; message: string } | { kind: "NotFound"; message: string } | { kind: "Config"; message: string } | { kind: "Serialize"; message: string } | { kind: "Request"; message: string } | { kind: "Zip"; message: string } | { kind: "Task"; message: string } | { kind: "Auth"; message: string } | { kind: "Credential"; message: string } | { kind: "Sync"; message: string };

/**  Returned by `check_book_file_state`: describes whether a book file is cached locally. */
export type FileStateDto = {
	path: string,
	localState: string,
	localSize: number | null,
};

/**  Request item for `check_book_file_states`. */
export type FileStateRequestDto = {
	bookId: number,
	format: string,
};

/**  与前端 `FixedLayoutSettings` 对齐，作为机器本地偏好持久化在 `config.json` 的 `readerUi` 字段。 */
export type FixedLayoutSettingsDto = {
	background?: string,
	navigationMode?: string,
	readingLayout?: string,
	displayMode?: string,
	spreadMode?: string,
	zoomMode?: string,
	direction?: string,
	brightness?: number | null,
	pageGap?: number | null,
};

export type FormatSize = {
	format: string,
	sizeBytes: number,
};

export type LibraryInfo = {
	id: string,
	name: string,
	path: string,
	bookCount: number,
	sourceType: string | null,
	dataSourceId: string | null,
	sourcePath: string | null,
};

export type NewLocalDataSourceInput = {
	name: string,
	rootPath: string,
};

export type NewOnedriveDataSourceInput = {
	name: string,
	clientId: string | null,
	tenantId: string | null,
	rootPath: string | null,
	userName: string | null,
	userEmail: string | null,
	refreshToken: string | null,
};

export type NewWebdavDataSourceInput = {
	name: string,
	endpoint: string,
	username: string,
	password: string,
	rootPath: string | null,
};

export type OnedriveAuthResultDto = {
	accessToken: string,
	refreshToken: string,
	userName: string,
	userEmail: string | null,
};

export type OnedriveFolderEntry = {
	name: string,
	path: string,
	itemId: string | null,
};

export type OnedriveStartAuthInput = {
	clientId: string | null,
	tenantId: string | null,
};

export type PaginatedBooks = {
	items: BookEntry[],
	total: number,
};

export type PreparedBookSource = {
	format: string,
	filePath: string,
	extractedDirPath: string | null,
	extractedEntries: string[],
	streamerUrl: string | null,
};

/**  A local reader highlight with an optional note attached to its Readium Locator. */
export type ReaderAnnotationDto = {
	id: string,
	libraryId: string,
	bookId: number,
	format: string,
	kind: string,
	locator: any,
	color: string,
	note: string | null,
	createdAt: number | null,
	updatedAt: number | null,
};

/**  A durable Readium Locator saved by the reader as an explicit bookmark. */
export type ReaderBookmarkDto = {
	id: string,
	libraryId: string,
	bookId: number,
	format: string,
	locatorKey: string,
	locator: any,
	createdAt: number | null,
	updatedAt: number | null,
};

export type ReaderSettingsDto = {
	theme?: string,
	fontFamily?: string,
	fontFamiliesByLanguage?: { [key in string]: string },
	fontSize?: number | null,
	lineHeight?: number | null,
	paddingX?: number | null,
	readingLayout?: string,
	textAlign?: string,
	colCount?: string,
};

export type ReaderUiPreferences = ReaderUiPreferences_Serialize | ReaderUiPreferences_Deserialize;

export type ReaderUiPreferences_Deserialize = {
	version?: number,
	appTheme?: string,
	appLanguage?: string,
	libraryViewMode?: string,
	detailFullScreen?: boolean,
	fixedLayout?: FixedLayoutSettingsDto,
} & {
	reflowable?: ReflowableReaderPreferencesDto,
} | {
	reflow?: ReflowableReaderPreferencesDto,
};

export type ReaderUiPreferences_Serialize = {
	version: number,
	appTheme: string,
	appLanguage: string,
	libraryViewMode: string,
	detailFullScreen: boolean,
	fixedLayout: FixedLayoutSettingsDto,
	reflowable: ReflowableReaderPreferencesDto,
};

export type ReadingPositionCandidateDto = {
	operationId: string,
	locator: any,
	displayProgression: number | null,
	recordedAt: number,
	replicaId: string,
};

/**  Returned by `get_reading_progress`: JSON of a Readium `Locator` (compatible with `@readium/shared`). */
export type ReadingProgressDto = {
	libraryId: string,
	bookId: number,
	format: string,
	locator: any,
	displayProgression: number | null,
	updatedAt: number | null,
};

export type ReflowTtsDto = {
	ttsConfigId?: string,
	ttsSpeed?: number | null,
};

export type ReflowableReaderPreferencesDto = {
	settings?: ReaderSettingsDto,
	tts?: ReflowTtsDto,
};

export type TestWebdavConnectionInput = {
	endpoint: string,
	username: string,
	password: string,
	rootPath: string | null,
};

export type WebdavFolderEntry = {
	name: string,
	path: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

