// Auto-generated typed Tauri IPC bindings.
// Re-export from tauri-specta.ts (generated by Rust `cargo test`).
export type * from "./tauri-specta"

import { demoCommands, isDemoApiEnabled } from "./demo-api"
import { type ErrorKind, commands as raw } from "./tauri-specta"

type Result<T> =
  | { status: "ok"; data: T }
  | { status: "error"; error: ErrorKind }

function unwrap<T>(promise: Promise<Result<T>>): Promise<T> {
  return promise.then((r) => {
    if (r.status === "error") {
      const err = new Error(r.error.message)
      ;(err as Error & { kind: string }).kind = r.error.kind
      throw err
    }
    return r.data
  })
}

function wrap<T, A extends unknown[]>(
  fn: (...args: A) => Promise<Result<T>>,
): (...args: A) => Promise<T> {
  return (...args: A) => unwrap(fn(...args))
}

const commands = isDemoApiEnabled()
  ? (demoCommands as unknown as typeof raw)
  : raw

export const api = {
  listLibraries: wrap(commands.listLibraries),
  listDataSources: wrap(commands.listDataSources),
  testWebdavConnection: wrap(commands.testWebdavConnection),
  webdavListFolders: wrap(commands.webdavListFolders),
  onedriveStartAuth: wrap(commands.onedriveStartAuth),
  addOnedriveDataSource: wrap(commands.addOnedriveDataSource),
  onedriveListFolders: wrap(commands.onedriveListFolders),
  addLibrary: wrap(commands.addLibrary),
  addWebdavLibrary: wrap(commands.addWebdavLibrary),
  addOnedriveLibrary: wrap(commands.addOnedriveLibrary),
  refreshLibrary: wrap(commands.refreshLibrary),
  refreshWebdavLibrary: wrap(commands.refreshWebdavLibrary),
  refreshOnedriveLibrary: wrap(commands.refreshOnedriveLibrary),
  addLocalDataSource: wrap(commands.addLocalDataSource),
  addWebdavDataSource: wrap(commands.addWebdavDataSource),
  removeLibrary: wrap(commands.removeLibrary),
  removeDataSource: wrap(commands.removeDataSource),
  switchLibrary: wrap(commands.switchLibrary),
  getActiveLibraryId: wrap(commands.getActiveLibraryId),
  getBooks: wrap(commands.getBooks),
  getBooksPage: wrap(commands.getBooksPage),
  getBookDetail: wrap(commands.getBookDetail),
  getSeriesBooks: wrap(commands.getSeriesBooks),
  listBookReadingFormats: wrap(commands.listBookReadingFormats),
  setBookReadingFormat: wrap(commands.setBookReadingFormat),
  listFavoriteBookIds: wrap(commands.listFavoriteBookIds),
  addFavoriteBook: wrap(commands.addFavoriteBook),
  removeFavoriteBook: wrap(commands.removeFavoriteBook),
  getReadingProgress: wrap(commands.getReadingProgress),
  listReadingProgress: wrap(commands.listReadingProgress),
  setReadingProgress: wrap(commands.setReadingProgress),
  getReaderUiPreferences: wrap(commands.getReaderUiPreferences),
  setReaderUiPreferences: wrap(commands.setReaderUiPreferences),
  prepareBookSource: wrap(commands.prepareBookSource),
  writeEpubReadiumManifest: wrap(commands.writeEpubReadiumManifest),
  setReaderTrafficLightsVisible: wrap(commands.setReaderTrafficLightsVisible),
  closeBookStreamer: wrap(commands.closeBookStreamer),
  syncDbForLibrary: wrap(commands.syncDbForLibrary),
  checkBookFileState: wrap(commands.checkBookFileState),
  checkBookFileStates: wrap(commands.checkBookFileStates),
  downloadBookFile: wrap(commands.downloadBookFile),
  deleteLocalBookFile: wrap(commands.deleteLocalBookFile),
  cancelBookDownload: wrap(commands.cancelBookDownload),
}
