// Auto-generated typed Tauri IPC bindings.
// Re-export from tauri-specta.ts (generated by Rust `cargo test`).
export type * from "./tauri-specta"

import { type ErrorKind, commands as raw } from "./tauri-specta"

type Result<T> =
  | { status: "ok"; data: T }
  | { status: "error"; error: ErrorKind }

function unwrap<T>(promise: Promise<Result<T>>): Promise<T> {
  return promise.then((r) => {
    if (r.status === "error") throw r.error
    return r.data
  })
}

function wrap<T, A extends unknown[]>(
  fn: (...args: A) => Promise<Result<T>>,
): (...args: A) => Promise<T> {
  return (...args: A) => unwrap(fn(...args))
}

export const api = {
  listLibraries: wrap(raw.listLibraries),
  listDataSources: wrap(raw.listDataSources),
  testWebdavConnection: wrap(raw.testWebdavConnection),
  addLibrary: wrap(raw.addLibrary),
  refreshLibrary: wrap(raw.refreshLibrary),
  addLocalDataSource: wrap(raw.addLocalDataSource),
  addWebdavDataSource: wrap(raw.addWebdavDataSource),
  removeLibrary: wrap(raw.removeLibrary),
  removeDataSource: wrap(raw.removeDataSource),
  switchLibrary: wrap(raw.switchLibrary),
  getActiveLibraryId: raw.getActiveLibraryId,
  getBooks: wrap(raw.getBooks),
  getBooksPage: wrap(raw.getBooksPage),
  getBookDetail: wrap(raw.getBookDetail),
  getSeriesBooks: wrap(raw.getSeriesBooks),
  getReadingProgress: wrap(raw.getReadingProgress),
  setReadingProgress: wrap(raw.setReadingProgress),
  getBookCover: wrap(raw.getBookCover),
  getReaderUiPreferences: wrap(raw.getReaderUiPreferences),
  setReaderUiPreferences: wrap(raw.setReaderUiPreferences),
  prepareBookSource: wrap(raw.prepareBookSource),
  writeEpubReadiumManifest: wrap(raw.writeEpubReadiumManifest),
  closeBookStreamer: wrap(raw.closeBookStreamer),
  getCacheUsage: wrap(raw.getCacheUsage),
  clearCache: wrap(raw.clearCache),
  enforceCacheLimit: wrap(raw.enforceCacheLimit),
  syncListBackends: wrap(raw.syncListBackends),
  syncTestBackend: wrap(raw.syncTestBackend),
  syncListFileStates: wrap(raw.syncListFileStates),
  syncDownloadFile: wrap(raw.syncDownloadFile),
  syncEvictLocalFile: wrap(raw.syncEvictLocalFile),
  syncDeleteFileEverywhere: wrap(raw.syncDeleteFileEverywhere),
  syncDbNow: wrap(raw.syncDbNow),
  syncDbForLibrary: wrap(raw.syncDbForLibrary),
}
