packages:
  - "packages/db"
  - "packages/tools"
  - "my-reader"
  - "my-reader-mobile"
patchedDependencies:
  "@react-native-menu/menu@2.0.0": "patches/@react-native-menu__menu@2.0.0.patch"
  "react-native-css@3.0.7": "patches/react-native-css@3.0.7.patch"
allowBuilds:
  '@sentry/cli': true
  edgedriver: true
  esbuild: true
  geckodriver: true
  msgpackr-extract: true
  unrs-resolver: true
overrides:
  lightningcss: 1.30.1
blockExoticSubdeps: false
