packages:
  - "packages/*"
  - "my-reader"
  - "my-reader-mobile"
allowBuilds:
  '@sentry/cli': true
  edgedriver: true
  esbuild: true
  geckodriver: true
  msgpackr-extract: true
  unrs-resolver: true
blockExoticSubdeps: false
