//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "book_cover_thumbnail_cache")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(unique_key = "idx_book_cover_thumbnail_cache_book_size_version")]
    pub book_id: i64,
    #[sea_orm(column_type = "Text")]
    pub cover_identity: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "idx_book_cover_thumbnail_cache_book_size_version"
    )]
    pub thumbnail_version: String,
    #[sea_orm(unique_key = "idx_book_cover_thumbnail_cache_book_size_version")]
    pub width_px: i64,
    #[sea_orm(unique_key = "idx_book_cover_thumbnail_cache_book_size_version")]
    pub height_px: i64,
    #[sea_orm(column_type = "Text")]
    pub file_name: String,
    pub file_size_bytes: i64,
    #[sea_orm(column_type = "Double")]
    pub created_at: f64,
    #[sea_orm(column_type = "Double")]
    pub updated_at: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
