//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "pending_book_imports")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub book_uuid: String,
    #[sea_orm(unique)]
    pub book_id: i64,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub authors_json: String,
    #[sea_orm(column_type = "Text")]
    pub format: String,
    pub size: i64,
    #[sea_orm(column_type = "Text")]
    pub sha256: String,
    #[sea_orm(column_type = "Text", unique)]
    pub relative_path: String,
    pub recorded_at_ms: i64,
    #[sea_orm(column_type = "Double")]
    pub created_at: f64,
    pub attempt_count: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_error: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
