// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "my-reader-core.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "NativeMyReaderCore.h"

@interface MyReaderCore : NSObject <NativeMyReaderCoreSpec>
#else
#import <React/RCTBridgeModule.h>

@interface MyReaderCore : NSObject <RCTBridgeModule>
#endif

@end