//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "books")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub title: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub sort: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub timestamp: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pubdate: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub series_index: Option<f64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub author_sort: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub isbn: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub lccn: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub path: Option<String>,
    pub flags: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub uuid: Option<String>,
    pub has_cover: Option<i64>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_modified: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
