//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "identifiers")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub book: i64,
    #[sea_orm(column_type = "Text", nullable)]
    pub r#type: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub val: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
