//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod annotations;
pub mod book_cover_thumbnail_cache;
pub mod book_reading_format;
pub mod bookmarks;
pub mod favorite_books;
pub mod file_state;
pub mod reading_completions;
pub mod reading_progress;
pub mod reading_sessions;
pub mod sync_automerge_changes;
pub mod sync_automerge_outbox;
pub mod sync_automerge_projection_meta;
pub mod sync_automerge_receipts;
pub mod sync_automerge_state;
pub mod sync_errors;
pub mod sync_local_meta;
pub mod sync_schedule_state;
