//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod authors;
pub mod books;
pub mod books_authors_link;
pub mod books_languages_link;
pub mod books_publishers_link;
pub mod books_ratings_link;
pub mod books_series_link;
pub mod books_tags_link;
pub mod comments;
pub mod data;
pub mod identifiers;
pub mod languages;
pub mod library_id;
pub mod publishers;
pub mod ratings;
pub mod series;
pub mod tags;
