// Generated by scripts/generate-reader-note-marker-template.mjs. Do not edit.
// Sources:
// - packages/tools/src/reader-note-marker/reader-note-marker.html
// - packages/tools/src/reader-note-marker/reader-note-marker.css
package com.myreader.readium.reader

internal object ReaderNoteMarkerTemplateSource {
  val ELEMENT = """
    <!--
      Shared reader note marker source template.
      After editing, run from the repository root:
      pnpm --dir my-reader-mobile prepare:reader-note-marker
    -->
    <div class="myreader-note-marker-anchor">
      <button type="button" class="myreader-note-marker-hit" data-activable="1" aria-label="{{accessibilityLabel}}">
        <span class="myreader-note-marker-note" aria-hidden="true">
          <span class="myreader-note-marker-paper" style="background-color: {{tint}} !important"></span>
        </span>
      </button>
    </div>
    """.trimIndent()

  val STYLESHEET = """
    /*
     * Shared reader note marker source template.
     * After editing, run from the repository root:
     * pnpm --dir my-reader-mobile prepare:reader-note-marker
     */
    .myreader-note-marker-anchor {
      overflow: visible;
    }

    .myreader-note-marker-anchor:not(:last-child) {
      display: none;
    }

    .myreader-note-marker-hit {
      appearance: none;
      -webkit-appearance: none;
      position: absolute;
      inset-inline-end: -{{hitOffset}}px;
      inset-block-start: -{{hitOffset}}px;
      display: grid;
      width: {{hitSize}}px;
      height: {{hitSize}}px;
      margin: 0;
      padding: 0;
      place-items: center;
      border: 0;
      background: transparent;
      cursor: pointer;
      pointer-events: auto;
      touch-action: manipulation;
      -webkit-tap-highlight-color: transparent;
    }

    .myreader-note-marker-note {
      --myreader-note-marker-size: 18px;
      --myreader-note-marker-opacity: 0.65;
      display: block;
      position: relative;
      width: var(--myreader-note-marker-size);
      height: var(--myreader-note-marker-size);
      overflow: visible;
      filter: drop-shadow(0 0 1px rgba(255, 255, 255, 0.9)) drop-shadow(0 1px 2px rgba(28, 23, 20, 0.3));
    }

    .myreader-note-marker-paper {
      position: absolute;
      top: 0;
      left: 0;
      display: block;
      width: var(--myreader-note-marker-size);
      height: var(--myreader-note-marker-size);
      border-radius: 2px;
      opacity: var(--myreader-note-marker-opacity) !important;
      clip-path: polygon(50% 0, 100% 0, 100% 100%, 0 100%, 0 50%);
      -webkit-clip-path: polygon(50% 0, 100% 0, 100% 100%, 0 100%, 0 50%);
    }

    .myreader-note-marker-paper::before {
      position: absolute;
      top: 0;
      left: 0;
      width: 50%;
      height: 50%;
      background: rgba(255, 255, 255, 0.58) !important;
      clip-path: polygon(100% 0, 100% 100%, 0 100%);
      -webkit-clip-path: polygon(100% 0, 100% 100%, 0 100%);
      content: "";
    }

    .myreader-note-marker-paper::after {
      position: absolute;
      top: 0;
      left: 0;
      width: 50%;
      height: 50%;
      box-sizing: border-box;
      border-inline-end: 1px solid rgba(255, 255, 255, 0.76);
      border-block-end: 1px solid rgba(255, 255, 255, 0.76);
      content: "";
    }
    """.trimIndent()
}
