// Generated by scripts/generate-reader-viewport-anchor.mjs. Do not edit.
// Source: packages/tools/src/reader-viewport-anchor.ts
package com.myreader.readium.reader

private val readerViewportAnchorRuntimeScript = """
    (function (window) {
      /**
       * Shared reader viewport-anchor source.
       * After editing, run from the repository root:
       * pnpm -C my-reader-mobile prepare:reader-viewport-anchor
       *
       * This is the only hand-written DOM implementation. The generator emits the
       * desktop TypeScript and the Swift/Kotlin scripts executed in EPUB web views.
       * Do not edit those generated files directly.
       */
      function cssEscape(window, value) {
          const css = window.CSS;
          if (typeof (css === null || css === void 0 ? void 0 : css.escape) === "function") {
              return css.escape(value);
          }
          return value.replace(/[^a-zA-Z0-9_-]/g, (character) => {
              var _a;
              return `\\${'$'}{(_a = character.codePointAt(0)) === null || _a === void 0 ? void 0 : _a.toString(16)} `;
          });
      }
      /** Prefers a unique ID, then falls back to a deterministic element path. */
      function stableCssSelector(window, element) {
          const document = element.ownerDocument;
          if (element.id) {
              const selector = `#${'$'}{cssEscape(window, element.id)}`;
              if (document.querySelectorAll(selector).length === 1)
                  return selector;
          }
          const parts = [];
          let current = element;
          while (current) {
              let part = current.localName;
              const currentName = current.localName;
              const parent = current.parentElement;
              if (parent) {
                  const siblings = [...parent.children].filter((sibling) => sibling.localName === currentName);
                  if (siblings.length > 1) {
                      part += `:nth-of-type(${'$'}{siblings.indexOf(current) + 1})`;
                  }
              }
              parts.unshift(part);
              if (current.id) {
                  const idSelector = `#${'$'}{cssEscape(window, current.id)}`;
                  if (document.querySelectorAll(idSelector).length === 1) {
                      parts[0] = idSelector;
                      break;
                  }
              }
              current = parent;
          }
          return parts.length > 0 ? parts.join(" > ") : null;
      }
      function firstTextDescendant(node) {
          var _a, _b;
          if (!node)
              return null;
          if (node.nodeType === Node.TEXT_NODE)
              return node;
          const walker = (_a = node.ownerDocument) === null || _a === void 0 ? void 0 : _a.createTreeWalker(node, NodeFilter.SHOW_TEXT);
          return (_b = walker === null || walker === void 0 ? void 0 : walker.nextNode()) !== null && _b !== void 0 ? _b : null;
      }
      function textPointAt(window, x, y) {
          var _a, _b, _c, _d, _e;
          const document = window.document;
          const caretPosition = (_b = (_a = document).caretPositionFromPoint) === null || _b === void 0 ? void 0 : _b.call(_a, x, y);
          if (caretPosition) {
              const node = caretPosition.offsetNode.nodeType === Node.TEXT_NODE
                  ? caretPosition.offsetNode
                  : ((_c = firstTextDescendant(caretPosition.offsetNode.childNodes[caretPosition.offset])) !== null && _c !== void 0 ? _c : firstTextDescendant(caretPosition.offsetNode));
              if (node)
                  return { node, offset: caretPosition.offset };
          }
          const caretRange = (_d = document.caretRangeFromPoint) === null || _d === void 0 ? void 0 : _d.call(document, x, y);
          if (!caretRange)
              return null;
          const node = caretRange.startContainer.nodeType === Node.TEXT_NODE
              ? caretRange.startContainer
              : ((_e = firstTextDescendant(caretRange.startContainer.childNodes[caretRange.startOffset])) !== null && _e !== void 0 ? _e : firstTextDescendant(caretRange.startContainer));
          return node ? { node, offset: caretRange.startOffset } : null;
      }
      /**
       * Keeps anchors on visible text and prevents splitting a UTF-16 surrogate pair.
       */
      function anchorCharacterOffset(text, requestedOffset) {
          var _a, _b, _c;
          if (text.length === 0)
              return 0;
          let offset = Math.min(Math.max(0, requestedOffset), text.length - 1);
          if (/\s/.test((_a = text[offset]) !== null && _a !== void 0 ? _a : "")) {
              for (let distance = 1; distance < text.length; distance += 1) {
                  const after = offset + distance;
                  if (after < text.length && !/\s/.test((_b = text[after]) !== null && _b !== void 0 ? _b : "")) {
                      offset = after;
                      break;
                  }
                  const before = offset - distance;
                  if (before >= 0 && !/\s/.test((_c = text[before]) !== null && _c !== void 0 ? _c : "")) {
                      offset = before;
                      break;
                  }
              }
          }
          const code = text.charCodeAt(offset);
          if (code >= 0xdc00 && code <= 0xdfff && offset > 0)
              return offset - 1;
          return offset;
      }
      function pointRect(document, point) {
          var _a, _b;
          const text = point.node.data;
          if (!text.trim())
              return null;
          const offset = anchorCharacterOffset(text, point.offset);
          const length = String.fromCodePoint((_a = text.codePointAt(offset)) !== null && _a !== void 0 ? _a : 0).length;
          const range = document.createRange();
          range.setStart(point.node, offset);
          range.setEnd(point.node, Math.min(text.length, offset + length));
          return (_b = range.getClientRects()[0]) !== null && _b !== void 0 ? _b : range.getBoundingClientRect();
      }
      /** Resolves a persisted DOM point to the single character used as its anchor. */
      function rangeForReaderViewportDomRange(window, domRange) {
          var _a, _b;
          const point = domRange.start;
          const element = window.document.querySelector(point.cssSelector);
          if (!element)
              return null;
          const textNodes = [...element.childNodes].filter((node) => node.nodeType === Node.TEXT_NODE);
          const node = textNodes[point.textNodeIndex];
          if (!node || node.data.length === 0)
              return null;
          const offset = anchorCharacterOffset(node.data, Math.min((_a = point.charOffset) !== null && _a !== void 0 ? _a : 0, node.data.length - 1));
          const length = String.fromCodePoint((_b = node.data.codePointAt(offset)) !== null && _b !== void 0 ? _b : 0).length;
          const range = window.document.createRange();
          range.setStart(node, offset);
          range.setEnd(node, Math.min(node.data.length, offset + length));
          return range;
      }
      /**
       * Samples around the viewport center and captures the closest rendered glyph.
       * Nearby samples handle centers that land in whitespace or between columns.
       */
      function captureReaderViewportAnchor(window) {
          var _a;
          const { document } = window;
          const centerX = window.innerWidth / 2;
          const centerY = window.innerHeight / 2;
          const offsets = [0, -0.08, 0.08, -0.16, 0.16];
          let best = null;
          for (const yOffset of offsets) {
              for (const xOffset of offsets.slice(0, 3)) {
                  const point = textPointAt(window, centerX + window.innerWidth * xOffset, centerY + window.innerHeight * yOffset);
                  if (!(point === null || point === void 0 ? void 0 : point.node.data.trim()))
                      continue;
                  const rect = pointRect(document, point);
                  if (!rect)
                      continue;
                  const distance = Math.hypot(rect.left + rect.width / 2 - centerX, rect.top + rect.height / 2 - centerY);
                  if (!best || distance < best.distance)
                      best = { point, rect, distance };
              }
          }
          if (!best)
              return null;
          const parent = best.point.node.parentElement;
          if (!parent)
              return null;
          const cssSelector = stableCssSelector(window, parent);
          if (!cssSelector)
              return null;
          const textNodes = [...parent.childNodes].filter((node) => node.nodeType === Node.TEXT_NODE);
          const textNodeIndex = textNodes.indexOf(best.point.node);
          if (textNodeIndex < 0)
              return null;
          const content = best.point.node.data;
          const charOffset = anchorCharacterOffset(content, best.point.offset);
          const highlight = String.fromCodePoint((_a = content.codePointAt(charOffset)) !== null && _a !== void 0 ? _a : 0);
          const before = content.slice(Math.max(0, charOffset - 32), charOffset);
          const after = content.slice(charOffset + highlight.length, charOffset + 33);
          return {
              cssSelector,
              domRange: {
                  start: { cssSelector, textNodeIndex, charOffset },
              },
              text: {
                  ...(before ? { before } : {}),
                  highlight,
                  ...(after ? { after } : {}),
              },
              yRatio: (best.rect.top + best.rect.height / 2) / window.innerHeight,
          };
      }
      /** Returns whether the persisted anchor character intersects the viewport. */
      function isReaderViewportAnchorVisible(window, domRange) {
          var _a, _b;
          return [
              ...((_b = (_a = rangeForReaderViewportDomRange(window, domRange)) === null || _a === void 0 ? void 0 : _a.getClientRects()) !== null && _b !== void 0 ? _b : []),
          ].some((rect) => rect.right > 0 &&
              rect.bottom > 0 &&
              rect.left < window.innerWidth &&
              rect.top < window.innerHeight);
      }
      /** Captures the anchor's normalized position before a reflow. */
      function readerViewportAnchorOffset(window, domRange) {
          var _a;
          const rect = (_a = rangeForReaderViewportDomRange(window, domRange)) === null || _a === void 0 ? void 0 : _a.getClientRects()[0];
          if (!rect || window.innerWidth <= 0 || window.innerHeight <= 0)
              return null;
          return {
              xRatio: (rect.left + rect.width / 2) / window.innerWidth,
              yRatio: (rect.top + rect.height / 2) / window.innerHeight,
          };
      }
      /** Restores the anchor's vertical viewport position after a reflow. */
      function restoreReaderViewportAnchorOffset(window, domRange, yRatio) {
          var _a;
          const rect = (_a = rangeForReaderViewportDomRange(window, domRange)) === null || _a === void 0 ? void 0 : _a.getClientRects()[0];
          if (!rect)
              return false;
          const targetY = yRatio * window.innerHeight;
          const currentY = rect.top + rect.height / 2;
          window.scrollBy(0, currentY - targetY);
          return true;
      }
      /** Captures the metrics used by platform adapters to detect settled layout. */
      function readerViewportLayoutState(window) {
          var _a, _b, _c, _d;
          const scrollingElement = window.document.scrollingElement;
          return {
              fontsLoaded: !window.document.fonts || window.document.fonts.status === "loaded",
              clientHeight: (_a = scrollingElement === null || scrollingElement === void 0 ? void 0 : scrollingElement.clientHeight) !== null && _a !== void 0 ? _a : window.innerHeight,
              clientWidth: (_b = scrollingElement === null || scrollingElement === void 0 ? void 0 : scrollingElement.clientWidth) !== null && _b !== void 0 ? _b : window.innerWidth,
              scrollHeight: (_c = scrollingElement === null || scrollingElement === void 0 ? void 0 : scrollingElement.scrollHeight) !== null && _c !== void 0 ? _c : 0,
              scrollWidth: (_d = scrollingElement === null || scrollingElement === void 0 ? void 0 : scrollingElement.scrollWidth) !== null && _d !== void 0 ? _d : 0,
          };
      }
      /** Compares only dimensions that change when EPUB pagination or reflow moves. */
      function sameReaderViewportLayout(first, second) {
          return Boolean(first &&
              first.clientHeight === second.clientHeight &&
              first.clientWidth === second.clientWidth &&
              first.scrollHeight === second.scrollHeight &&
              first.scrollWidth === second.scrollWidth);
      }
      return {
        captureReaderViewportAnchor: captureReaderViewportAnchor,
        isReaderViewportAnchorVisible: isReaderViewportAnchorVisible,
        readerViewportLayoutState: readerViewportLayoutState,
        restoreReaderViewportAnchorOffset: restoreReaderViewportAnchorOffset
      };
    })
""".trimIndent()

internal val captureReaderBookmarkAnchorScript = """
JSON.stringify(($readerViewportAnchorRuntimeScript)(window).captureReaderViewportAnchor())
""".trimIndent()

internal fun readerViewportAnchorOffsetRestoreScript(
  domRangeJson: String,
  yRatio: Double
): String = """
JSON.stringify(($readerViewportAnchorRuntimeScript)(window).restoreReaderViewportAnchorOffset($domRangeJson, $yRatio))
""".trimIndent()

internal val readerViewportLayoutStateScript = """
JSON.stringify(($readerViewportAnchorRuntimeScript)(window).readerViewportLayoutState())
""".trimIndent()

internal fun readerBookmarkVisibilityScript(domRangeJson: String): String = """
JSON.stringify(($readerViewportAnchorRuntimeScript)(window).isReaderViewportAnchorVisible($domRangeJson))
""".trimIndent()
