[package]
name = "my-reader-core-ffi"
version = "0.12.0"
edition.workspace = true

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
my-reader-core.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uniffi = { workspace = true, features = ["tokio"] }

[dev-dependencies]
rusqlite.workspace = true
tempfile = "3"
