export const DEVELOPER_TOOLS_ENABLED =
  __DEV__ || process.env.EXPO_PUBLIC_ENABLE_PERF_TOOLS === "true"

export const LIBRARY_CARD_SEGMENT_PROFILER_ENABLED =
  process.env.EXPO_PUBLIC_ENABLE_LIBRARY_CARD_SEGMENT_PROFILER === "true"
