import { sqliteTable, text } from "drizzle-orm/sqlite-core"

/** Local Automerge replica identity for the current library. */
export const syncLocalMeta = sqliteTable("sync_local_meta", {
  /** 32-character UUID. */
  id: text("id").notNull().primaryKey(),
  /** Active sidecar protocol identifier. */
  protocol: text("protocol").notNull(),
  /** Stable Calibre library UUID used to prevent segments from different libraries from mixing. */
  libraryUuid: text("library_uuid").notNull(),
  /** UUIDv4 writer identity generated by this installation for this library. */
  replicaId: text("replica_id").notNull(),
})
