import { sqliteTable, text } from "drizzle-orm/sqlite-core"

/** Local sidecar sync identity and segment sequence state for the current library. */
export const syncLocalMeta = sqliteTable("sync_local_meta", {
  /** 32-character UUID. */
  id: text("id").notNull().primaryKey(),
  /** Active sidecar protocol identifier, such as library-sidecar-v4. */
  protocol: text("protocol").notNull(),
  /** Stable Calibre library UUID used to prevent segments from different libraries from mixing. */
  libraryUuid: text("library_uuid").notNull(),
  /** UUIDv4 writer identity generated by this installation for this library. */
  replicaId: text("replica_id").notNull(),
  /** Sequence of the next local segment to prepare, stored as decimal text to preserve u64. */
  nextSequence: text("next_sequence").notNull().default("1"),
})
