[package]
name = "myreader-rust-components"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[features]
bindgen = ["uniffi/cli"]

[dependencies]
myreader-core.workspace = true
myreader-sync.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
uniffi.workspace = true

[dev-dependencies]
rusqlite.workspace = true
tempfile = "3"

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"
required-features = ["bindgen"]
