//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod annotations;
pub mod book_reading_format;
pub mod bookmarks;
pub mod favorite_books;
pub mod file_state;
pub mod reading_progress;
pub mod sync_meta;
