//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "sync_automerge_changes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text", unique)]
    pub change_hash: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "idx_sync_automerge_changes_actor_sequence"
    )]
    pub actor_id: String,
    #[sea_orm(
        column_type = "Text",
        unique_key = "idx_sync_automerge_changes_actor_sequence"
    )]
    pub actor_sequence: String,
    #[sea_orm(column_type = "Blob")]
    pub bytes: Vec<u8>,
    #[sea_orm(column_type = "Text")]
    pub origin: String,
    pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
