#ifndef MYREADERCORE_H
#define MYREADERCORE_H
// Generated by uniffi-bindgen-react-native
#include <ReactCommon/CallInvoker.h>
#include <cstdint>
#include <jsi/jsi.h>

namespace myreadercore {
using namespace facebook;

uint8_t installRustCrate(jsi::Runtime &runtime,
                         std::shared_ptr<react::CallInvoker> callInvoker);
uint8_t cleanupRustCrate(jsi::Runtime &runtime);
} // namespace myreadercore

#endif /* MYREADERCORE_H */