// Generated by uniffi-bindgen-react-native
#include "my-reader-core.h"
#include "bindings/my_reader_core_ffi.hpp"

namespace myreadercore {
using namespace facebook;

uint8_t installRustCrate(jsi::Runtime &runtime,
                         std::shared_ptr<react::CallInvoker> callInvoker) {
  NativeMyReaderCoreFfi::registerModule(runtime, callInvoker);
  return true;
}

uint8_t cleanupRustCrate(jsi::Runtime &runtime) { return false; }
} // namespace myreadercore